### ISSUE TITLE
Consider refactor of Habitat constructor to accept population grid rather than boolean activity grid

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#10]
https://github.com/ScottishCovidResponse/Simulation.jl/blob/master/examples/Epidemiology/Scotland_SIR_example.jl#L26 accepts an `active` grid. Change functionality so that it accepts `scotpop`.

**Comment by claireh93** [comment]
And so that this demographic information feeds into populating the `EpiLandscape` automatically.

**Comment by sdl1** [comment]
Taking a look at this, the cleanest way seems to be to make `simplehabitatAE` accept `scotpop`, figure out `dimension` and `active` automatically from that, and then save `scotpop` as a field `initial_susceptibles` (or something) in `GridEpiEnv`. Then when `EpiSystem` is constructed it can pull this information to populate its landscape automatically.

 I'll try this, unless there are other preferences? (@claireh93)
