### ISSUE TITLE
Check .gitignore is OK (e.g. ignore .pyc files, source data, output .pdfs?)

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#105]
Produce a `.gitignore` to be agreed by team.

**Comment by bobturneruk** [comment]
Should not ignore files in `sample_input_files`

**Comment by bobturneruk** [comment]
Useful https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by bobturneruk** [comment]
@magicicada - should `withAges.pdf` be part of the repo. as an example output, or should it be removed + ignored as other `.pdfs`?

**Comment by magicicada** [comment]
@bobturneruk withAges.pdf should be removed and ignored
