### ISSUE TITLE
Develop an output formats plan

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#107]
Decide (liaising with consortium management) on output formats for this repository. These might include:

- GeoTIFF
- Shapefile
- HDF5

Raise additional issues to implement output in code and to document.

**Comment by richardreeve** [comment]
This (and #108) should be a general issue across all models, as should #9... maybe we should have a cross-model meeting about them?

**Comment by bobturneruk** [comment]
Perhaps folks from other repos could apply their labels to this issue? And use this as a place for discussion? Happy to participate in a meeting.

**Comment by bobturneruk** [comment]
This function is the current interim output for simple_network_sim and relates to this issue https://github.com/ScottishCovidResponse/simple_network_sim/blob/d8c47fa621e7c47576f026330d2076c308d29cdd/simplestNetworkSim_covidAdapted.py#L295

**Comment by bobturneruk** [comment]
This is part of data pipeline / API and visualisation, and no longer something that needs to be done in simple network sim other than for development and model refinement for which specific issues will be raised.
