### ISSUE TITLE
Extend simplehabitatAE grids to read climate data

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#11]
Relates #3 #10

**Comment by claireh93** [comment]
At the moment the only "climate" information is a simple constant background temperature. Functions for connecting data from other climate systems need to be created for the epi branch (as they are in the main biodiversity code).

**Comment by richardreeve** [comment]
Can we not use common code between the two rather than duplicating it?

**Comment by claireh93** [comment]
Yes that's a fair point, although some of the biodiversity ones do specific things, like using `budget` information (solar energy, water etc.) that was needed for plants and not for this.

**Comment by claireh93** [comment]
Waiting on climate data, but should be available shortly.

**Comment by jwscook** [comment]
@claireh93 I'm just going through all the issues to tidy up and was wondering if the climate data available yet?

**Comment by claireh93** [comment]
Not as far as I'm aware, @richardreeve do we have an update on this?

**Comment by claireh93** [comment]
Picking up on this now!
