### ISSUE TITLE
A Plan for Continuous Management of Data from Central Repository to Model 

### ISSUE THREAD

**Issue by thibaud-porphyre** [ScottishCovidResponse/SCRCIssueTracking#118]
As of now, data are extracted from gitHub and processed using R to a format readable in c++. We need a more streamline process directly in the model.  

See also #225 
See also #440 
See also #437

**Comment by qingfengxia** [comment]
C++ is not really the language for data plot(viz) and preprocessing data.  Have you/anyone considered the reversed way, keep the workflow at bash shell, or R/python level.

If what we needs a program take file name as input parameter (R numeric vector is fine), and output data file, then the bash shell workflow is fine.

If only several API will be exported to R/Python,  then it is straight-forwards to use Rcpp to expose C++ API to R. I can do it. We can discuss in the next zoom meeting.

**Comment by peter-t-fox** [comment]
Closing this issue as it has been made obsolete by the work on the data pipeline.
