### ISSUE TITLE
Switch CMake configuration to use Clang

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#119]
Code was originally developed using Clang. CMakeLists.txt presently uses g++, which can be an alias for Clang++ on some platforms, but not everywhere. Change the CmakeLists to enforce use of Clang as a requirement, so that everyone is using the same environment.

**Comment by kzscisoft** [comment]
Not sure you can do this, looking it up it seems that CMake just uses whatever is set by `CXX` and `CC` environment variables, it has no control over forcing these. I am looking into adding Clang to the GitHub actions.

**Comment by qingfengxia** [comment]
in CI script:   `CXX=clang++  cmake ..`   end even debug/release switch, C++ std version, this is the recommended way to change cmake options.

**Comment by kzscisoft** [comment]
@qingfengxia Yes once step ahead of you on that (See https://github.com/ScottishCovidResponse/Covid19_EERAModel/commit/0d8897b4af76472f9a1ecbf65df2af7f9dba1b2b)

**Comment by qingfengxia** [comment]
sorry, for my outdated comment, as I have not catch up the situation.  I thought it was an issue at the dicussion stage.



________________________________

**Comment by kzscisoft** [comment]
@qingfengxia please don't apologise, it is great to have you on the team :)
