### ISSUE TITLE
Create canonical integration test / example to refactor / development against

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#12]
We need to make sure that we concentrate on the important features. These features will be in this integration test / example. Hence refactoring should never break this, but we may end up breaking the less important examples / integration tests.

**Comment by jwscook** [comment]
Need to be able to run this locally and in CI. Should be as fast as possible.

 - 20 mins for a entire year, with timestep is a year.

So need to configure this integration test to run for 10, 50, 100, 365 days.

**Comment by claireh93** [comment]
Initial thoughts include a fairly small test grid (which could run much faster than whole Scotland/UK mentioned above), with different mixing rates and high transmission parameters.

**Comment by claireh93** [comment]
Closed for now with ScottishCovidResponse/Simulation.jl#19.
