### ISSUE TITLE
Performance optimisation

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#123]
Moves on from #7 #6 

Use the benchmarking and profiling tools e.g. https://github.com/tkluck/StatProfilerHTML.jl to find bottlenecks and make performance improvements.

**Comment by wytbella** [comment]
Is the "bottleneck" here "time" bottleneck? If you want to check the "memory" bottleneck, we have to consult to other pkgs.
