### ISSUE TITLE
Make `EpiSystems` comparable with one another to enable easier testing

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#13]
To guard against new bugs we need to be able to compare the numbers in an EpiSystem with the numbers in another one via `isapprox`. The key quantity to compare is the `abundances` property.

**Comment by sdl1** [comment]
Hello, a couple of questions on this:
- Is it only the `abundances` field that we want to compare, or should any others be included?
- What kind of norm(s) would be appropriate for comparing two systems for this purpose? E.g. L1 (=sum of absolute differences of each class in each grid square), etc.

thanks!

**Comment by eperim** [comment]
Would simply using AutoHashEquals (https://github.com/andrewcooke/AutoHashEquals.jl) do the trick here?

**Comment by sdl1** [comment]
Yeah that may work for exact comparison, but probably not for approximate comparisons?

**Comment by jwscook** [comment]
The primary use case is for regression testing since there isn't a full test suite. We need to know that the code under development is only changing the output to a few epsilon hence the suggestion of `isapprox`. When the code is "working" we can add `L1`, `L2`, and `LInf` norms for comparing outputs for research purposes.

**Comment by eperim** [comment]
I am not sure how autohashequals works under the hood, but I think it works with floats as well. IIRC that work for the SyntheticGrids.jl package at least: https://github.com/invenia/SyntheticGrids.jl/blob/master/src/grid.jl#L1
https://github.com/invenia/SyntheticGrids.jl/blob/master/test/runtests.jl#L107
(ages I don't touch that package, so I might be missing something)

**Comment by sdl1** [comment]
Yeah it should work with any type, but AFAIK it can only check for strict equality, whereas we want to consider approximate equality (i.e. are two systems "close enough")

It could be good to add it anyway, for full equality checks of the whole struct. I had a quick try but realised it would need to be added to a bunch of structs all over the codebase to work properly, since (I think) you need to add it all down the nesting hierarchy:
```julia
julia> struct Bar
       a::Vector
       end

julia> @auto_hash_equals struct Foo
       b::Bar
       end

julia> Foo(Bar([1, 2])) == Foo(Bar([1, 2]))
false # because Bar doesn't have auto_hash_equals
```

**Comment by eperim** [comment]
I linked the synthetic grids example because it includes fields with floats, so at least that it can compare fine. But I guess if you want custom `rtol` and `atol` it indeed won't work.

**Comment by sdl1** [comment]
Can this issue be closed after https://github.com/ScottishCovidResponse/Simulation.jl/pull/14 or is any other functionality needed?
