### ISSUE TITLE
Add a function to read the age-class mixing matrix

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#134]
We have an age-mixing matrix in format visible in sample_20200327_comix_social_contacts.sampleCSV
that gives mean number of contacts per day from one age band (the row labels) to another age band (the column labels). I would like a function that reads a file in this format and returns a nested dictionary indexed by tuples that describe the age ranges and with values that are the floating-point content of the matrix.

Eg from the file sample_20200327_comix_social_contacts.sampleCSV

The age range [0,5) has an expected 0.033775387 interactions per day with the age range [5,18). I would therefore like the dictionary you return (say its called returnDict) to have as the value at:
returnDict[(0,5)][(5,18)]
the floating point number:
0.033775387

**Comment by magicicada** [comment]
We have an age-mixing matrix in format visible in sample_20200327_comix_social_contacts.sampleCSV
that gives mean number of contacts per day from one age band (the row labels) to another age band (the column labels). I would like a function that reads a file in this format and returns a nested dictionary indexed by tuples that describe the age ranges and with values that are the floating-point content of the matrix.

Eg from the file sample_20200327_comix_social_contacts.sampleCSV

The age range [0,5) has an expected 0.033775387 interactions per day with the age range [5,18). I would therefore like the dictionary you return (say its called returnDict) to have as the value at:
returnDict[(0,5)][(5,18)]
the floating point number:
0.033775387

**Comment by WPettersson** [comment]
I've done some work on this on a [branch in my repo](https://github.com/WPettersson/simple_network_sim/blob/issue-134-read-age-class-mixing-matrix/mixing_matrix.py) but it might be over-engineered, so just looking for feedback as to whether it's going to be too complicated to be useful. If so, I'll scale back to just a dict-of-dict type approach. The advantage I see of what I've got is that it can accept the `(0,5)` notation for age ranges, as well as just the string `[0,5)`. I threw in the handling of exact ages as a bonus, wasn't sure if that would be useful.

Usage would include:

        mm = MixingMatrix("sample_input_file/sample_20200327_comix_social_contacts.sampleCSV")
        print(mm[28][57])  # Prints the expected number of interactions a 28 year old
                           # would have with a 57 year old in a day
        print(mm["[30,40)"]["70+"])  # Prints the expected number of interactions someone in the
                                     # age range [30-40) would have with someone aged 70 or older
                                     # in any given day.
        print(mm[(30,40)]["70+"])  # As above

Note that I have not yet implemented testing for this, that was next though.

**Comment by magicicada** [comment]
I like it, and think it will be useful to this model.  It's maybe a bit much for this, but particularly as it's a standalone bit of code that's not really a problem as I see it.

**Comment by WPettersson** [comment]
Closed in https://github.com/ScottishCovidResponse/simple_network_sim/pull/21
