### ISSUE TITLE
Make `EpiSystem` writeable to disk

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#14]
Use `JLD2.jl` for this (which is actually hdf5 under the hood)

**Comment by eperim** [comment]
Should we consider JLSO as an alternative? https://github.com/invenia/JLSO.jl

The advantage is that it saves the environment, which can help with reproducibility. Apparently, the only drawback is that it cannot serialise files larger than a couple GB.

**Comment by jwscook** [comment]
JLSO.jl looks good! I don't suppose output files will reach a GB, but please correct me @claireh93

**Comment by claireh93** [comment]
Saving a Scotland-sized EpiSystem at the moment is about 160Mb - although I suppose this will grow with more categories like ages.

**Comment by eperim** [comment]
Can we close this since https://github.com/ScottishCovidResponse/Simulation.jl/pull/13 has been merged?
