### ISSUE TITLE
benchmark canonical tests

### ISSUE THREAD

**Issue by wytbella** [ScottishCovidResponse/SCRCIssueTracking#140]
Change the benchnark from scrips in `examples/Epidemiology/` to those in `test/canonical/`

A few questions,

- Is it ok to benchmark each individual files, or it's strictly required to benchmark `simulate!` only? @claireh93 

- If we want to benchmark part of the file, I might have to copy files to `benchmark/` and do some edit there. This means we keep the same set of canonical scripts in two places, which is not ideal. Any suggestions how to avoid this? How to ensure things get automatically updated from one place to another? @jwscook

**Comment by jwscook** [comment]
It would be good to refactor the benchmark to accept a cached dependency (the kind that takes 10 mins to create but I've forgotten its name). Then the benchmark can amortise initialisation and the measurement will be essentially be of the main loop.

**Comment by wytbella** [comment]
> refactor the benchmark to accept a cached dependency

You mean to load the precomputed environment as a JLSO file? This JLSO file is saved by running those canonical test files? Everytime the canonical test get updated, we just save a new JLSO to run benchmark on?

> the kind that takes 10 mins to create but I've forgotten its name)
Not sure I know what you refer to

**Comment by jwscook** [comment]
I don't know - it was mentioned in the chat yesterday. Can you run it and find out what happens before the main loop? If there is a anything that can be saved e.g. as a JLSO file, make that happen. Then for future benchmarks it will be possible to load that straight in and skip the set up. This issue requires some research on your part, so don't be put off by not knowing the answers - no one does.

**Comment by claireh93** [comment]
Ah are we talking about the `EpiSystem` here? We have functionality to save that now as a result of #14. This sounds like a great idea, and would need the canonical tests to save the outputs in a cache. Then you could just load them in and benchmark `simulate!(epi, timestep)`.
