### ISSUE TITLE
Non-deterministic crashes

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#145]
After merging the chrispooley branch (commit 937433263e732677110e99fbb5452c1244d27245), I get non-deterministic errors when running on macOS when compiled using Apple Clang ("g++").  These errors happen with the serial build.  Sometimes it is a segmentation fault, sometimes a check error (I think).  Sometimes it completed without errors.

To reproduce:
```
(set -e; i=0; while true; do printf "\n### Running BICI iteration $i ###\n\n"; rm -rf Output; ./bici Scotland_bici_input.xml 1000; i=$((i+1)); done)
```
The output is:
```
...
### Running BICI iteration 8 ###

CoronaBICI running in serial
Reading input file...
Initialising...
Initialising individual 0 / 5438100
...
Initialising individual 5400000 / 5438100
Check
$ echo $?
139
```

I don't know why the error message is not reported (is there a signal handler in BICI?), but exit code 139 is 128+11, i.e. signal 11, segmentation fault.

- [ ] Get a better understanding of these errors.
- [ ] Get a backtrace using the debugger
- [ ] See if they also happen with -O0
- [ ] See if they also happen in Linux.
- [ ] See if they happen in macOS with GCC.

Before this merge, macOS runs would fail as in #32.  Chris mentioned that he fixed a bug which might have caused #32.

**Comment by WPettersson** [comment]
I checked with Valgrind, and there seem to be a number of memory leaks and invalid memory reads. These can often cause non-deterministic crashes such as these, depending on what was stored in memory before running bici.

I've tracked down some to check.h:345, where the code calls a switch statement on an invalid read, and with no default case, which could potentially cause a crash, so might be worth investigating.

**Comment by ianhinder** [comment]
Thanks!  I am running a stress test on linux, and it's reached 421 runs of the same code without crashing, whereas on my laptop, it always tends to crash before 10 or so.  The main difference is the compiler (GCC vs Apple Clang).  There's of course the possibility that it's a compiler bug, but much more likely it just doesn't happen to show up with the way the code is compiled with GCC, and it's due to the issues that you raise.  Valgrind was going to be one of my next steps 🙂  

I did run [clang analyser](https://clang-analyzer.llvm.org) on the code, and it finds a lot of switch statements with no default cases which potentially could lead to uninitialised variables being used.  See here: https://scottishcovidresponse.github.io/CoronaBICI/static_analysis/.  That's for commit bd74eeed, I'll set up something more consistent later.

Do you have some time to work on this?  Perhaps you could go through and add fatal errors in switch statements identified?

**Comment by WPettersson** [comment]
I also did try the mass runs with both GCC and CLANG, and reached the same results as you (many runs, zero crashes). It might be a compiler thing, I do know that recently (GCC7 I think?) they made some changes that would avoid crashes on accessing uninitialised memory, but I don't have any specifics.

I'll have a go through today/soon and add some error checking on all these switch statements and see what I can find, but I haven't experienced the crashes yet and don't have a Mac system so I cannot test for that in particular.

**Comment by ianhinder** [comment]
Feel free to commit the error checking on the switch statements to a branch.  I just tried the stress test with MacPorts gcc8 8.4.0_0 on my mac, and it failed after the first Check with
```
e|ERROR MSG: Check: EC61:4.98288e+06    Sample number:0
```

**Comment by ianhinder** [comment]
Maybe macOS initialises process memory differently to Linux.

**Comment by ianhinder** [comment]
Actually, we don't have to go to the trouble of running the static analyzer. Compiling with -Wall is enough to find lots of possible issues.  I think clearing these compiler warnings should be a high priority.  Can I leave this with you? Do you have some time to devote to this at the moment?

**Comment by WPettersson** [comment]
I'm happy to go through the warnings that pop up. Some of them I've already inspected, in particular there are a few indentation warnings where the code looks like

    for (int j =0 j < size; ++j) do_x(j); do_y();

In some cases, I'm confident the code is correct, but sometimes I'm plain not sure. With those, I may have to ask questions.

**Comment by ianhinder** [comment]
I've created #152 specifically about compiler warnings and assigned it to you.

**Comment by ianhinder** [comment]
The original problem with nondeterministic crashes when running on macOS appears to have been solved when the code in the confidence interval calculations was [corrected](https://github.com/ScottishCovidResponse/CoronaBICI/commit/1350774f8aabdcb377873b03436e354f47e88ec8); this also fixed valgrind errors.  Closing ticket.
