### ISSUE TITLE
Lazy load optionally dependency packages e.g. MPI with Requires.jl

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#146]
MPI isn't needed for serial or threaded runs, so it Requires.jl might speed up loading time if it used to configure the project to ignore MPI in these cases. If it doesn't speed things up, then scrap it and keep it simple.

**Comment by mohamed82008** [comment]
It's also about the simplicity of installation, no need to have MPI setup to get Simulation.jl running.

**Comment by jwscook** [comment]
Yes that's very true @mohamed82008 . It's a better solution to build times than #87 by far. Don't ask me how many hours I've waited for Travis builds to fail....
