### ISSUE TITLE
Cleanup lookup table generation

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#149]
The _lookup function (starting at line 477 in https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/src/Biodiversity/Ecosystem.jl) is responsible of generating a table per species of what probability it has of moving over the local area according to a kernel. This is one of the first things I wrote 4 years ago and it's horrible code! I think cleaning this up will really help us for future things, like having a more complex spatial structure.

**Comment by claireh93** [comment]
At the moment it searches through a grid of relative moves (e.g. move 1 grid cell to the North, 1 to the west) and calculates the probability of making this move through integrating the dispersal function (`dispersalfn`) over the area.

**Comment by claireh93** [comment]
In order to do less computation, it only does this for one corner of the kernel, and fills in the rest symmetrically using the function `_symmetric_grid` (line 426).

**Comment by claireh93** [comment]
The epi code also relies on this architecture, even though it is written in the biodiversity side of the code. If anyone can think of a way for this to be better structured and cleaner, that would be great!

**Comment by jwscook** [comment]
Julia is unable to specialise on arguments specified as `Function` e.g.

```julia
foo(input::Function) = ... input ... 
```

There might be a significant speed up changing to e.g.

```julia
foo(input::T) where {T<:Function} = ... input ... 
```

I'll make a PR

**Comment by claireh93** [comment]
Ahh good to know! There might be a couple of those throughout the codebase

**Comment by jwscook** [comment]
OK. I'll hunt some down and fix those in the this PR.
