### ISSUE TITLE
Test issue 5

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#159]

**Comment by ianhinder** [comment]
@ richardreeve

**Comment by ianhinder** [comment]
@richardreeve

**Comment by richardreeve** [comment]
That got through (the latter).

**Comment by richardreeve** [comment]
@IanHinder

**Comment by richardreeve** [comment]
It automatically corrects the capitalisation when you do it by hand, but I guess not when github-actions does it.

**Comment by richardreeve** [comment]
Incidentally, weirdly the first (@ richardreeve) one sent me a message too. I don't know why...
