### ISSUE TITLE
Get travis working for epi branch

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#16]

**Comment by AlexRobson** [comment]
Picked this up to start working with the code

I have got Travis installing MPI and correctly building RCall, but I"m hitting the errors in https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/17

https://github.com/ScottishCovidResponse/Simulation.jl/tree/ar/travis

Is the julia version of 1.3.2 meant to be 1.3.1?

**Comment by jwscook** [comment]
It looks like 1.3.2 not available as a download. Setting to 1.3.1 would be fine.

**Comment by richardreeve** [comment]
Are we not going to run this with 1.4.0 given it's the latest (non-LTS) version?

**Comment by jwscook** [comment]
It can be whatever you like - 1.5-dev even. But it's only important in the short term to make it run with the version that exists on the platform where it will run. Which one is that?

**Comment by richardreeve** [comment]
Well, we're going to be running it on DiRAC, and as far as I know julia isn't currently installed, so we can choose, but we may as well go for 1.4.1?

**Comment by claireh93** [comment]
Simulation#epi tests currently fail as I hadn't updated them after a structure change - I'll fix that today.

**Comment by claireh93** [comment]
Okay, so for this PR (https://github.com/ScottishCovidResponse/Simulation.jl/pull/2) the tests all pass for me now on 1.4.1, but I had to set OnlineStats@1.2.0 and Phylo@0.3.3 for this. Does that work for you Alex?

**Comment by AlexRobson** [comment]
Thanks! I've done some package version changes with those downgrades and now bumping up against some of the other installation prerequisites listed in #17. This is the R package dependency. Working through these now, they will all have to be added to the travis script anyway.  

Project.toml needs some package versioning I think.

**Comment by richardreeve** [comment]
It would be great to add this in if you can work out what it needs - I can no longer run the test scripts on my computer and I could a couple weeks ago... package versioning constraints have been killing me recently!

**Comment by AlexRobson** [comment]
This is working now on 1.4: https://travis-ci.org/github/ScottishCovidResponse/Simulation.jl/builds/680763877

1.0.5 is failing though due to package resolution.

**Comment by claireh93** [comment]
That's great, thanks Alex! Just so you are aware, as of this morning I have merged epi back into master so we can all work off the master branch more directly. Perhaps these changes could be merged directly back into master once they are resolved?

**Comment by AlexRobson** [comment]
Thanks. I've rebased onto your changes. Here's an MR for this: https://github.com/boydorr/Simulation.jl/pull/1

I just set 1.0.5 to allow faiures for now...

**Comment by jwscook** [comment]
> I just set 1.0.5 to allow faiures for now...

agreed

**Comment by AlexRobson** [comment]
This should have closed with !5
