### ISSUE TITLE
Confirm provenance of IniFile parser

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#172]
The original code contains a parser for `.ini` files used to extract input parameters from the `parameters.ini` file at the start of each run. This code is very different in style from the rest of the repository. Need to confirm its source and make sure that its license is compatible with ours.

**Comment by thibaud-porphyre** [comment]
This piece of code was a hand me down code from a colleague at SBio (school of Biology in Edinburgh Uni). TBH, I am not even sure that he coded it himself (maybe from the web).

**Comment by peter-t-fox** [comment]
> This piece of code was a hand me down code from a colleague at SBio (school of Biology in Edinburgh Uni). TBH, I am not even sure that he coded it himself (maybe from the web).

Okay, is it possible for you to ask him about its source?

**Comment by peter-t-fox** [comment]
Closing as we probably won't be able to find an answer to this.

**Comment by rwj11** [comment]
The code linked from https://www.codeproject.com/Articles/8342/CIniFile-Class-for-C-A-robust-cross-platform-INI-f looks familiar.  The licence is here https://www.codeproject.com/info/cpol10.aspx

**Comment by peter-t-fox** [comment]
Added reference to the source to the project docs.
