### ISSUE TITLE
Refactor and test DistanceComputation module

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#173]
In a similar manner to the `Utilities` module, the `DistanceComputation` module contains some duplicated code which could easily be simplified.

Tasks:

- [x] `sse_calc` and `sse_calc_int` functions should be merged via templates. Same for `sst_calc` and `sst_calc_int`.
- [x] Functions should throw a verbose exception if the simulated hospital and observed hospital data structures are not of the same size, rather than printing a warning message
- [x] The core loop which calculates the sum of squared errors is similar  in all five functions, and can probably be refactored out.

**Comment by kzscisoft** [comment]
Turns out only one function `sse_calc_int` is actually used in these files, all the rest can be scrapped

**Comment by peter-t-fox** [comment]
> 
> 
> Turns out only one function `sse_calc_int` is actually used in these files, all the rest can be scrapped

@thibaud-porphyre Do you have an opinion about this? Is there any chance you will need these functions again in the future, or is it a safe bet that only `sse_calc_int` is required?

**Comment by kzscisoft** [comment]
@peter-t-fox I noticed that this also seems to be the case in Utilities too, I think to be cautious maybe I should switch to Templates for both as opposed to deleting?

**Comment by peter-t-fox** [comment]
@kzscisoft Don't worry about it. I would:

* Only keep the code that is actually used
* Delete any unused functions
* If you wind up with only a single function left in DistanceComputation, I would move that function into Utilities and delete the DistanceComputation files. There's no point in having a dedicated module for a single function which is effectively a utility anyway.

We can always retrieve the deleted code and template it in the future if necessary, but since none of the functions are presently used, I prefer to delete rather than keeping them hanging around for no clear reason.

**Comment by kzscisoft** [comment]
@peter-t-fox Ok I am going to close the pull requests I have open at the moment and combine this with the work I am doing on Utilities

**Comment by thibaud-porphyre** [comment]
Sorry guys. I have been busy yesterday on other things. see_calc_int is likely to be use now. However, once we have more data from the consortium, I might have to use additional observation data to drive the inference. I cannot saw, then, if I will use them or not. However, as you mentioned, these can be easily retrieve at a later stage

**Comment by kzscisoft** [comment]
@peter-t-fox Are we ok to now close this issue?
