### ISSUE TITLE
Isolation and quarantine following exposure

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#177]
Need to incorporate individual level isolation and quarantine following contact. So in the model people are challenged with infection when they are in the same place as an infectious person, need some way of keeping a tag on this.

**Comment by paulbessell** [comment]
This is not an easy thing to model. Need to attribute a tag to people when they are chellenged with infection and then do tracing and isolation based some probability of self-isolation.

**Comment by johnnonweiler** [comment]
@paulbessell - We have people entering quarantine in the current model.  Please could you either close this issue, or explain what remains to be done?

**Comment by paulbessell** [comment]
We have reached a point wiht this one, the next issue to consider will be the contact tracing issue
