### ISSUE TITLE
Model public transport

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#178]
Currently there is no travel in there, but some fraction will travel to work or shops or school via public transport. This requires some way of clustering people, because people will typically travel together with the same-ish people

**Comment by paulbessell** [comment]
Currently we model people travelling to work but not how they travel. Could we incorporate some sort of mode of transport to and from work places and have people mixing on this. It would most likely be best mmodelled as another CommunalPlaces Class, with some probability thta each Person uses public transport

**Comment by BlairArchibald** [comment]
Implemented in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/105
