### ISSUE TITLE
Add a range of business sizes to the model

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#180]
Currently businesses are the same size and so have approximately equal numbers of customers and workers. Business sizes and footfall should vary around some distribution.

**Comment by paulbessell** [comment]
Currently business sizes are defined in the Population.createMixing() method, all business are similar size such that when people are assigned a workplace if they are designated as an office worker they are equally likely to be assigned to any office. In offices are different sizes, so the probabilities should vary

**Comment by BlairArchibald** [comment]
As a heads up if anyone takes this issue - I'm currently working on some place refactorings that should make this sort of thing much easier. Same with picking larger shops etc when going for a shopping trip.
