### ISSUE TITLE
Model business opening hours and shift workers

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#181]
Currently businesses are open for set hours and staff work all those hours. We need an efficient way to vary this so people work shifts.

**Comment by paulbessell** [comment]
Currently, business opening and lcosing hours are defined in the CommunalPlaces and its daughters as the startTime and endTime and opening days are defined bu the startDay and ednDay variables. All business are active for those hours and people that work at the businesses work for these hours. In reality, particularly for shops, restaurants and hospitals people will work variable days and shifts. This needs to be incorporated in some sensible way, but I canit figure it out exactly.

**Comment by BlairArchibald** [comment]
Merged in f5141dc
