### ISSUE TITLE
Clean up READMEs

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#185]
We should only have one README file.  (Please make one file, and review the contents.)

**Comment by johnnonweiler** [comment]
I'm assigning Blair to this because he seems to have mostly done it already!

**Comment by BlairArchibald** [comment]
@paulbessell Can you please add the "Background" section to README.md describing a bit about the modelling approach/limits/uses from an epidemiological perspective? 

We should remove the old README file (non Markdown). Could someone with repo rights do this, it's not worthy of a pull request.
