### ISSUE TITLE
Add unit tests for the simulation.imported.utils package

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#187]
Note that these utils have probably all been copied from the Contact-Tracing-Model project, and they may already be developing tests there (or might want any tests that we create).

**Comment by johnnonweiler** [comment]
We should check which of these imported classes are actually being used, and remove the ones that aren't.

**Comment by vinopm** [comment]
As discussed, I'll pick this up

**Comment by vinopm** [comment]
I feel like we should avoid manually copying over classes (with their tests) from project to project. How about having a separate project with common classes/utils and then we can import them in via gradle into these two projects? @johnnonweiler thoughts?

**Comment by johnnonweiler** [comment]
I think that there's currently not a lot in common between the two projects, and it's better to keep things simple (and separate) for the moment.  If we start sharing more code, then we should think again.

**Comment by johnnonweiler** [comment]
I should emphasize that probably some of the imported classes are not being used and should be removed (rather than adding their tests).

**Comment by vinopm** [comment]
Okay sure, I'll have a look at it.

**Comment by vinopm** [comment]
https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/24
