### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#204]
It would be really useful to have some more advanced docs, something like: https://richardreeve.github.io/Diversity.jl/latest/
with a link to the latest/dev version on the GitHub front page. 

For now this could be built based on the information in README and Structure.md / Design.md, although incorporating installation instructions from #17 would be handy too.

**Comment by claireh93** [comment]
Incidentally, does anyone know an easy way to write equations for GitHub docs? It seems like it doesn't pick up latex style syntax, and so my solution so far was to use a python tool that automatically converted my equations to svgs and included them in Structure_gh.md. But I feel like surely there must be a simpler way to do this!

**Comment by sdl1** [comment]
Quick question @claireh93 , is the only difference between `Structure.md` and `Structure_gh.md` the equation formatting? If so I'll probably just keep `Structure.md` for this PR, and try to make the equations format nicely in the rendered docs (so they probably won't work viewing directly in GitHub, but that shouldn't be a problem once the hosted docs are up)

**Comment by claireh93** [comment]
Hi Sean, yes they are no different in terms of content and that sounds ideal about the hosted docs - will make life much easier for keeping them updated - thanks!
