### ISSUE TITLE
Epidemiological process to be simplify

### ISSUE THREAD

**Issue by thibaud-porphyre** [ScottishCovidResponse/SCRCIssueTracking#207]
There was a mistake in which frailty measure to be used in the model. Correct values did not improve fitting performance and show lack of power to infer some parameters. The epi process needs to be simplify to improve inference quality and speed. 

Note that the regression tests will need to be updated for this when it is done.

**Comment by thibaud-porphyre** [comment]
Model is now simplify. It account for capacity of beds in hospital dedicated for COVID. Some of the information is currently hard coded. Parameters.ini need to be changed accordingly.

**Comment by peter-t-fox** [comment]
@thibaud-porphyre Do you need someone to review these changes and merge them into `dev`? If so, please create a pull request for the appropriate branch, specifying what changes need to be made to the `parameters.ini` file, and also whether or not the reference outputs in the regression tests will need to be updated. I can then assign someone to do this.

**Comment by thibaud-porphyre** [comment]
Hi Peter. I am still working on it. I will create a pull request asap.

**Comment by thibaud-porphyre** [comment]
Pull request has be created.

**Comment by thibaud-porphyre** [comment]
data and .ini file added as a separate repository in the test folder.

**Comment by richardreeve** [comment]
@thibaud-porphyre just to let you know the `model reconstruction` tag is really for the LSHTM and Imperial model reconstruction work.

**Comment by peter-t-fox** [comment]
Closed with merge of EERA PR #19
