### ISSUE TITLE
Create regression test

### ISSUE THREAD

**Issue by aflag** [ScottishCovidResponse/SCRCIssueTracking#208]
My suggestion is that we start off by creating a simple regression test on basicSimulation. For this, I suggest we pass in the random generator (random.Random) as a parameter of basicSimulation. Alternatively, we could make basicSimulation competely deterministic by receiving a list of first infected people as a parameter (maybe this is not realistic as the function may have other sources of randomness in future). I believe this test is sort of an easy win for us to be able to refactor and move bits of the code around without risking breaking it.

**Comment by bobturneruk** [comment]
So looking at this again, unless I'm missing something, it seems [basicSimulation](https://github.com/ScottishCovidResponse/simple_network_sim/blob/d8c47fa621e7c47576f026330d2076c308d29cdd/simplestNetworkSim_covidAdapted.py#L273) is not currently in use. Do we want [basicSimulationInternalAgeStructure](https://github.com/ScottishCovidResponse/simple_network_sim/blob/d8c47fa621e7c47576f026330d2076c308d29cdd/simplestNetworkSim_covidAdapted.py#L326)?

I've really not have much time with the actual code so I could be chatting nonsense here! Also, are there any other calls to `random.*` as a result of running the function that we need to control seeds for?

@magicicada - do you have a preference on setting seeds or having (in effect) a pre-randomised test input?

**Comment by aflag** [comment]
There's a single call for random, which is selecting the first people that will be infected in the current code. As far as I know, only  basicSimulationInternalAgeStructure is currently in use, not  basicSimulation. My idea here was to add this test with the least amount of changes to the actual code, but I plan on making basicSimulationInternalAgeStructure take an instance of Random as a parameter in my next task, which will involve more unit tests.

**Comment by bobturneruk** [comment]
Fanstastic! Thanks!
