### ISSUE TITLE
Find a contact who can explain how LSHTM model is intended to be run

### ISSUE THREAD

**Issue by alysbrett** [ScottishCovidResponse/SCRCIssueTracking#210]
@kzscisoft said today that he has been able to run the model but is not sure if what he is running is the full thing or just some limited demo. If we have any contacts with the team behind the model or anyone else who has worked with it at all it would be useful to have someone to ask questions about intended usage and related things like the relevance of some unavailable files that appear to be needed.

In today's meeting, Elaine and David didn't have any direct contacts who could help so we thought we should ask Louise.

**Comment by richardreeve** [comment]
Unfortunately we don't know anyone either. I'm hoping that @eaferguson or @dpascall will be able to work out what it ought to be doing from the paper, but if not then I think the best thing to do is to raise an issue in the parent repository if anything is unclear. If not then we can trying contacting Adam Kucharski, but no-one really knows him and he's going to be super busy...

**Comment by alysbrett** [comment]
Yes, @kzscisoft has raised an issue on the parent repo and had a response I think... can you link to it here please Kristian?

**Comment by kzscisoft** [comment]
Hi @alysbrett @richardreeve  here is the link to the issue. Someone has replied but they do not seem to be actually answering what I said from what I can determine, they seem to go completely off topic.

https://github.com/cmmid/covid-uk/issues/5

**Comment by alysbrett** [comment]
I think it is someone else who is trying to run the model. They do give a link to a relevant issue about the dropbox file thing but then also raising their own separate issues about a specific scenario.

**Comment by richardreeve** [comment]
It looks like nicholasdavies responded to that closed issue, so it may be worth coming up with a specific question and @'ing him directly. What exactly do you want to know in the first instance?

**Comment by Koesters** [comment]
```
# Set path
# Set this path to the base directory of the repository.
covid_uk_path = "."

# covidm options
cm_path = paste0(covid_uk_path, "/covidm/");
if (grepl(Sys.info()["user"], pattern = "^adamkuchars(ki)?$")) { cm_path = "~/Documents/GitHub/covidm/" }
source(paste0(cm_path, "/R/covidm.R"))
```
Just set covid_uk to **.**

**Comment by Koesters** [comment]
For compiling on Windows 10 with RTools 4.0.0 please see this issue in the original repo. 

cmmid/covid-uk/issues/6 #

**Comment by Koesters** [comment]
I have cloned and modified your fork and it runs fine on my system. 

Your fork is outdated in so far as there is some extra code and Data (see Google Mobility Report, now in the original 
https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv

Global Mobility in data could be updated to the newest if that is needed.
https://www.google.com/covid19/mobility/

**Comment by kzscisoft** [comment]
@Koesters If you look at the repository you will see there is another branch `kzscisoft-dev` in which I have applied the updates you mention to our own version. Yes we can get it to run.

We are looking to determine the point at which we can set our own parameter values when running the script. 

However I noticed some inconsistencies between the code in the paper in terms of the values of `Ip`, `E`, `Is` in the `UK.R` script (e.g. `Is` is stated as being taken from the gamma distribution `dS` within the paper defined as gamma(mu=5,k-4), but within the code it is defined instead as gamma(mu=3.5,k=4) which seems to be the value stated in the paper for `dC`) , as well as the presence of a variable `Ia` not described within the paper.

**Comment by Koesters** [comment]
> We are looking to determine the point at which we can set our own parameter values when running the script.
> 
> However I noticed some inconsistencies between the code in the paper in terms of the values of `Ip`, `E`, `Is` in the `UK.R` script (e.g. `Is` is stated as being taken from the gamma distribution `dS` within the paper defined as gamma(mu=5,k=4), but within the code it is defined instead as gamma(mu=3.5,k=4) which seems to be the value stated in the paper for `dC`) , as well as the presence of a variable `Ia` not described within the paper.

It seems (Guess) to me Ia that this is an addition of ASYMPTOMATIC cases.


> exposed individuals of age i will develop either a clinical infection
> with probability yi , or a subclinical infection with probability 1 ­ yi

Maybe someone dissolved this connection and gave them their own class between running the model for the paper and publishing it on the 1st of April 

In my version in covid_params.R there is a function 
``` cm_base_pop_SEI3R 
        dE  = cm_delay_gamma(4.0, 4.0, t_max = 60, t_step = 0.25)$p, # Derived from Backer et al Eurosurveillance
        dIp = cm_delay_gamma(2.4, 4.0, t_max = 60, t_step = 0.25)$p, # Derived from Backer et al Eurosurveillance
        dIa = cm_delay_gamma(7.0, 4.0, t_max = 60, t_step = 0.25)$p, # Assumed 7 days subclinical shedding
        dIs = cm_delay_gamma(3.2, 3.7, t_max = 60, t_step = 0.25)$p, # **Zhang et al 2020**
        dH = 1, # hospitalization ignored
        dC = 1, # no case reporting delay
```
Zhang et al was officially published on the 27.April so they must be referring to a preprint
https://github.com/cmmid/covid-uk/blob/aa373fce4d3c65b1fd954f85769a692095434291/covidm/R/covidm_params.R 

Zhang et al is also not in the bibliography of 
https://cmmid.github.io/topics/covid19/reports/uk_scenario_modelling_preprint_2020_04_01.pdf

So I assume the whole code is some form of intermediary between the run for the paper and the time it was posted on GITHUB. 

The paper also states 
>"After an incubation period lasting **4 days** on average"
but in the table S1 it is Incubation period (E to IC; days) d ; **mean 5.5** days E + dP Derived

Of course the details only the authors can know exactly. 

The paper was published over two months ago and the values will change as new knowledge comes in. Maybe unlike Physics, Biology, especially in an ongoing epidemic the values are not determined by 100% known universal laws? 

I can ask on the RAMP forum, there are people looking at the model if you are not in it.

Apologies for anything you already know and I mentioned.

**Comment by Koesters** [comment]
Someone on RAMP says

> An interactive version of a (not sure exactly which) LSHTM transmission model is now available here: https://cmmid.github.io/visualisations/covid-transmission-model.
> 
> I am not sure whether this is the COVID-UK Model (the ‘about’ section refers to it.
> 
> It is also useful to look at the paramters used in the model - although I believe the default parameters used in the app are not the same as the default parameters on the COVID-UK github model (https://github.com/cmmid/covid-uk) as **R0 in the app defaults to 2.4 whereas the R0 when running the github model churns out R0 = 3.26044660116393 (haven’t checked how).**
> 
> Also useful to see the age-specific contact matrices in the ‘age-specific parameters’ tab. Note two things about these:
> 
> it seems to assume that very few teachers are aged 50 or above (i.e. dark blue in these rows/columns) - I will see if I can find these matrices on the github page
> ‘children are assumed to be less susceptible to infection’ (from the ‘about’ tab). Not sure where this is in the app parameters. This would seem to contradict the ONS population surveys (e.g. Fig 3 in https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/conditionsanddiseases/bulletins/coronaviruscovid19infectionsurveypilot/england14may2020 (a later version has been published today))

so parameters change all the time
