### ISSUE TITLE
Swap Out Hard Coded Data in LSHTM Model?

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#226]
Currently a lot of data used by the LSHTM is hard coded (no separate data files but rather the data strings are defined within the main `UK.R` script). Might be a good idea to replace these few lines with external imports especially if we plan on using our own data. Even if we plan to only change the parameters layout wise this would be "tidier" and easier to follow.

**Comment by richardreeve** [comment]
This is definitely important. Once we understand what these are - @dpascall @eaferguson - we can separate them out and hopefully add them into our data pipeline so we can replace them with better estimates if we have them...
