### ISSUE TITLE
Move comments to docstrings

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#230]
Many of the functions in `simple_network_sim` are preceded by useful comments explaining what the function does. I propose that these are converted into "docstrings" and that the [sphinx docstring format](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) is adopted (this is a simple, well understood format).

This will:
- Ensure a minimum level of documentation is consistently applied across the project
- Enable IDEs to automatically provide function tooltips
- Enable automatic compilation of API documentation e.g. using readthedocs.org
- Create a precedent for documenting new functions etc.

**Comment by bobturneruk** [comment]
Relates to SCRC-113

**Comment by bobturneruk** [comment]
@magicicada and @aflag - happy with this in prinicple?

**Comment by aflag** [comment]
Sounds good to me!

**Comment by magicicada** [comment]
Strongly agree.

**Comment by bobturneruk** [comment]
Superseded by:

- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/295
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/296
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/297
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/298
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/299
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/300
- https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/301
