### ISSUE TITLE
Could use another Java developer

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#233]
We could use another experienced Java developer (with a significant proportion of their time available) to help with some of the core work on the Covid_Simulation_Model project (and potentially help out with the Contact-Tracing-Model too).

(There are also specific issues, marked "Find someone", suitable for Java developers joining on a more adhoc basis.)

I'm adding this issue following @alysbrett's request for general notes about where additional developers would be helpful.

**Comment by alysbrett** [comment]
Thanks. For the record, John and I + others have been discussing overall supply and demand for Java software engineers in a Zulip chat this afternoon and will use that to keep track of progress towards filling this request.

**Comment by johnnonweiler** [comment]
Although it's likely that we could easily use another developer, the need is less clear at the moment.
