### ISSUE TITLE
Uninitialised variable i in init.h

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#234]
Commit [092fda94f](https://github.com/ScottishCovidResponse/CoronaBICI/commit/092fda94f0d49316bd4a5d490bafa8baab33815e) removed a line initialising a variable, but the variable is still used.  This looks like an error.

```
diff --git a/Analysis/header/init.h b/Analysis/header/init.h
index 187779e..57cc7b3 100644
--- a/Analysis/header/init.h
+++ b/Analysis/header/init.h
@@ -8,7 +8,6 @@ void init()
   vector <long> eqfl;
 
   for(ob = 0; ob < nobs; ob++){
-    i = obsi[ob];
     indobs[i].push_back(ob);
     indobst[i].push_back(obst[ob]);
   }
```

**Comment by chrispooley** [comment]
Dear William,

Thank you very much for spotting this erroneous line deletion. I have no idea how that happened!

Cheers

Chris
