### ISSUE TITLE
Possible typo in output.h

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#236]
output.h contains a complex constant 45174i which is almost certainly not what was intended, causing compilation failure with the intel compiler.  This was introduced in [814f1a18 ](https://github.com/ScottishCovidResponse/CoronaBICI/commit/814f1a18).

```
     for(e = 0; e < nev; e++){
                        savesim >> t >> tr;
-                       if(i == 415091 && e == 2) t += 0.1;
+                       
+                       if(i == 196638 && e == 2) t += 0.01;
+                       if(i == 45174i&& e == 2) t += 0.1;
+                       
```

**Comment by chrispooley** [comment]
This typo has been corrected.
