### ISSUE TITLE
Timestamp model output files

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#245]
Related to #94

The output text files form the model do not indicate when they were generated or anything about the configuration that was in use when they were produced. This is not great for traceability.

The names of the files should be updated to include a time stamp at which they were produced, identical to the timestamp used for the log files in `outputs/logs`.

If the timestamp for the model run is determined in the `main` function, then it should be a simple matter of passing the timestamp to the `IO::WriteOutputsToFiles` function, and having it include that timestamp in the names of the outputs files.

**Note:** Annoyingly though, this will complicate running the regression tests, as the compare script will have to be aware that the reference outputs in the regression test directories have different filenames to those in the `outputs` directory. Maybe it would make more sense to create a time-stamped directory name for the outputs, rather than for the individual files? The benfit of this is that we could potentially add other useful files to this directory, such as a record of what code configuration was in use (commit hash etc.)

**Comment by thibaud-porphyre** [comment]
Agree. This log will be critical when we will run the code over all uk and for different scenario and time period

**Comment by kzscisoft** [comment]
> Note: Annoyingly though, this will complicate running the regression tests, as the compare script will have to be aware that the reference outputs in the regression test directories have different filenames to those in the outputs directory. Maybe it would make more sense to create a time-stamped directory name for the outputs, rather than for the individual files? The benfit of this is that we could potentially add other useful files to this directory, such as a record of what code configuration was in use (commit hash etc.)

I think creating directories may not be possible (see https://github.com/ScottishCovidResponse/Covid19_EERAModel/pull/24).

**Comment by peter-t-fox** [comment]
@kzscisoft You can use a library such as Boost.Filesystem (https://www.boost.org/doc/libs/1_72_0/libs/filesystem/doc/index.htm) to create directories, rather than having to make calls to ``system``. C++ has no built-in filesystem support before C++17.

The only downside of this is adding a new dependency to the project.
