### ISSUE TITLE
Use python's logging library

### ISSUE THREAD

**Issue by aflag** [ScottishCovidResponse/SCRCIssueTracking#251]
We've been using print to log things in the code so far, if we use python's logging we can benefit from log levels and possibly sending logs over to other streams rather than stdout.

**Comment by bobturneruk** [comment]
Moving from `print` to `logging` changed my life. I strongly feel that we should do this.

https://docs.python.org/3/library/logging.html

**Comment by magicicada** [comment]
I have never used this, but am willing to learn on this strong recommendation.

**Comment by bobturneruk** [comment]
It's so good. You'll never `print` again. Maybe sometimes.

**Comment by bobturneruk** [comment]
This has been implemented in `sampleUseOfModel.py` but print is still used in `network_of_populations.py`.

**Comment by widdowquinn** [comment]
Resolved with [PR #45 in `simple_network_sim`](https://github.com/ScottishCovidResponse/simple_network_sim/pull/45)
