### ISSUE TITLE
Document CI

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#254]
- Relevant links to travis and codecov
- How do these services interact with GitHub for this project

In readme for now.

**Comment by alex-konovalov** [comment]
Also add badges to the readme to display status and ease navigation.

**Comment by aflag** [comment]
This is the part that the org admins had to do:

Go to: https://travis-ci.org/github/ScottishCovidResponse/simple_network_sim and enable it

Go to codecov https://codecov.io/gh/ScottishCovidResponse/simple_network_sim and enable it

**Comment by alex-konovalov** [comment]
In https://github.com/ScottishCovidResponse/simple_network_sim/pull/28, I've added to the readme badges which look like these [![Build Status](https://travis-ci.org/ScottishCovidResponse/simple_network_sim.svg?branch=master)](https://travis-ci.org/ScottishCovidResponse/simple_network_sim) [![Code Coverage](https://codecov.io/github/ScottishCovidResponse/simple_network_sim/coverage.svg?branch=master&token=)](https://codecov.io/gh/ScottishCovidResponse/simple_network_sim) to help to find CI reports quickly.
