### ISSUE TITLE
split my_model() or make a class (to simplify parameter passing and unit test)

### ISSUE THREAD

**Issue by qingfengxia** [ScottishCovidResponse/SCRCIssueTracking#256]
This is kind of code refactoring,  it may break the code, so will need to be carefully and well planned. 

The reason is: 
1) this function is impossible to unit test
2) too many parameter, hard to remember

At this stage,  I hope to hear from the author and other developers
1) Is OO/class refactoring an acceptable way?   optional , it should make model more readable, but ti will break the code. 

2)  split this function into several functions,  compulsary, it should not break the code.  
RSE can do it. 

The below suggestions apply also to issue #256.

## Code review and suggested approach
The signature of `my_model` at present is 
```
void my_model(std::vector<double> parameter_set, std::vector<::EERAModel::params> fixed_parameters,
				std::vector<std::vector<double>> cfr_byage, std::vector<double> pf_byage,
				std::vector<std::vector<double>> waifw_norm,
				std::vector<std::vector<double>> waifw_sdist, std::vector<std::vector<double>> waifw_home,
				int duration, seed seedlist, int day_shut, std::vector<int> agenums, 
				double tau, gsl_rng * r, std::vector<int> &sim_status,std::vector<std::vector<int>> &ends,
				std::vector<int> &death_status,std::vector<int> &deathH_status)
```
- [x] Since the model's purpose is to return the 4 time series `sim_status`, `ends`, `death_status`, and `deathH_status`, it would make sense to create a structure (called something like `struct ModelOutputs`, which captures the outputs. Then the call to `my_model` would look more like
```
ModelOutputs outputs = my_model(...
```
This would also clean up the function signature significantly.
- [x] Similarly, the data structures `cfr_byage`, `pf_byage`, `waifw_norm`, `waifw_sdist`, and `waifw_home` are all used as parameters. It would make sense to group them into a single data structure which contains all of these as elements. This would again simplify the function signature. 
- [x] The `duration` and `tau` parameters are only used in one place, and are combined to determine the number of loops to run through in the model. They could easily be combined into a single parameter. 
- [ ] The parameter `parameter_set` contains the hypothesized parameter values generated for this model run: it should be declared `const` in the function signature.
- [ ] It may also make sense to combine the `parameter_set` and `fixed_parameters` data structures into a single data structure.

More generally, if we move to having the model be an instance of a `class Model`, then it would make sense to incorporate the following parameters into the model via passing parameters to the constructor e.g.
```
Model myModel(std::vector<::EERAModel::params> fixed_parameters,
				std::vector<std::vector<double>> cfr_byage, std::vector<double> pf_byage,
				std::vector<std::vector<double>> waifw_norm,
				std::vector<std::vector<double>> waifw_sdist, std::vector<std::vector<double>> waifw_home,
				seed seedlist, int day_shut, std::vector<int> agenums, 
				double tau, gsl_rng * r);
```
and then execute the model for a given set of hypothesized parameters via:
```
ModelOutputs outputs = myModel.Run(std::vector<double> parameter_set, int duration);
```
This would clarify the behavior of the code a great deal, as it makes clear the distinction between parameters that are fixed for all model runs, and those which potentially vary between runs

**Comment by peter-t-fox** [comment]
@qingfengxia Thanks for looking at this. At the moment, my preference is for splitting large functions into smaller ones which can effectively be tested. I think that going to a full object-oriented rewrite of the code may be too ambitious. So I would go for option (2), at first. In the long run, once we have confidence that we understand the code better, I think we will be in a better position to maybe go for option (1).

Can you potentially perform a code review, for this function, similar to what I have done in #250 ? The main things to identify are:

1. Any unused code, or code that could be simplified
2. Good places to split the function. (If variables passed into the function are only used in one part of the function, that would be a good place to consider splitting the function.)
3. Places where the code is unclear and could be made clearer with better names for variables and data structures.
4. Anything else you can think of...

**Comment by thibaud-porphyre** [comment]
Maybe this is what you mean by (2) but a third option would be to keep the my_model function as big but fragmenting its code into multiple functions that are easy to test. We won't be able to test the my_model function but if all the small one are tested and OK, it must be ok too.

**Comment by richardreeve** [comment]
Hi @qingfengxia - just so you know `model reconstruction` as a tag is really intended for the reconstruction of LSHTM and Imperial models within our framework...

**Comment by qingfengxia** [comment]
sounds great!


Qingfeng Xia
Senior Research Software Engineer, Culham Centre of Fusion Energy, UKAEA

https://github.com/qingfengxia
https://www.researchgate.net/profile/Qingfeng_Xia
personal website: https://www.iesensor.com

________________________________

**Comment by kzscisoft** [comment]
I will now work on merging those two parameter lists as suggested so we can close this issue.

**Comment by peter-t-fox** [comment]
Closing this as it is a legacy issue which has largely been overtaken by subsequent developments.
