### ISSUE TITLE
Switch to reading inputs via command line arguments

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#258]
Currently the configuration of model runs is done within the code itself, ideally we want to be able to pass parameters/data inputs via command line arguments.

**Comment by thibaud-porphyre** [comment]
what do you mean by "the configuration of model runs is done within the code itself"? Parameters and model runs configurations are all provided in the parameters.ini file. only the data are hard-coded.

**Comment by kzscisoft** [comment]
Hi @thibaud-porphyre my mistake, I got confused with the other model I am working on where both apply. Let me retitle it.

**Comment by kzscisoft** [comment]
Additional Note: Make sure file paths and any other arguments added are all clearly written to the log file during a run.
