### ISSUE TITLE
Epidemiological Expertise

### ISSUE THREAD

**Issue by sam-brett** [ScottishCovidResponse/SCRCIssueTracking#260]
## Background

There are a few areas in the code where I have had to make judgement calls in light of not having a background in virus modelling/policy. Apologies, this is a bit of a brain dump These are explained below:

1. If a person tests negative after being alerted, should they go into a new ISOLATION category, or the existing ALERTED or NONE

2) a) I have added tuneable delays in testing. This means a patient could change status before a test is carried out. Can/would a dead person be tested?  
 b) Would a recovered person test negative?

3) The health parameter of an individual is a uniform random number between 0 and 1. Can you suggest a function or distribution to use to make this more realistic as this impacts 4, 5 and 6. I'm thinking this could be perturbed by the age and gender fields?

4) At the moment the test for if someone goes into Asymptomatic or Symptomatic is based on their health parameter. If their health is < 0.5 they transition to symptomatic. Can be replaced with dice roll?

5) If a persons health is < 0.3 they will die after becoming symptomatic. Can be replaced with dice roll?

6) Similarly to health, the compliance is a uniform random number from 0 to 1. This isn't used anywhere yet. Does this logic sound ok: two people who would meet in normal circumstances each have a compliance field, say 0.4 and 0.6. One of them is alerted should their interaction be based on the minimum compliance value or the average of the two? This would result in either a 60% or 50% chance they would meet respectively.

**Comment by sibylleM** [comment]
Hi @sam-brett and @vinopm, here is our take on the issues listed above:
(1) If a person tests negative after being alerted, they should go into the NONE category.

(2)(a) Though there are some countries doing post-mortem test examinations this is beyond the scope of our model and we'll leave that out.

(2)(b) A recovered person should test negative.

(3)The health parameter is what Paul and Thibaud called frailty score and it would definitely be good to have that in the model. We are trying to request data for this, which we'll discuss at tomorrow's modelling meeting at 3pm. So for now we should leave it as it is and then get parameter estimations from the data (though we could also use health / age or a combination).

(4) and (5): This again depends on requested data. For now we should replace it by dice roll but should retain the other functionality so we could go back to it with appropriate values.

(6) The compliance value might be a nice scenario to explore or to do some sensitivity analysis on it. There are definitely scenarios where a minimum value would be appropriate or where a maximum value would make more sense, but for now the average value might be a good choice.

Also, besides 'compliance', could you please add an 'uptake' field? We'd like to evaluate what the optimal proportion of app uptake should be in a population. 

I hope this made sense and we can further discuss tomorrow morning. I'll join the meeting a little later as I accidentally double-booked myself.

Thanks very much @sam-brett & @vinopm!
