### ISSUE TITLE
Rename Household lists

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#267]
There are lists of people in the Household class with names like 'people' and 'vPeople', (as well as neighbours and visitors,) and the purpose of the different lists is not obvious.  It looks like there's room for making the implementation of this class easier to understand.

**Comment by BlairArchibald** [comment]
I agree - there's also possibly scope to push this into the super "Place" class such that each place has a "primary" (i.e. workers or inhabitants) and "visitors" list (possibly even sets since we don't need the ordering).

**Comment by BlairArchibald** [comment]
Merged in f72418ec6f801c2d540f92752fab74f4d36b437b
