### ISSUE TITLE
Handling new demographic data

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#270]
We now have a temporary repository with Scotland census data in hdf5 format, broken down by age into 5 year categories, at https://github.com/ScottishCovidResponse/temporary_data.
This needs to be fed into the model example run: Scottish_run.jl (still pending PR ScottishCovidResponse/Simulation.jl#38) instead of the current .tif file.
In the first instance this will probably need to be the 10km grid instead of 1km and will involve some kind of mapping between the grid id numbers supplied with the data and the x,y position in space, which should be available soon.

**Comment by claireh93** [comment]
Data format looks to be an array of `grid id`s, with associated population sizes broken down by ages for each.

**Comment by claireh93** [comment]
The grid IDs themselves are [row#]-[column#] (e.g. 1-1, 1-2, 1-3, 2-1, etc.) starting in the bottom left corner for the 10km grid of Scotland. These are only for land locations, so we would need to convert this to a full grid (i.e. involving some blank sea) in order for the simulation to run in its current format.

**Comment by eperim** [comment]
When I open it here, the `grid_id`s show just as some integer, and not as [row#]-[column#]. Example:
```julia 
(grid_id = 1260.0, 0-4 = 147.0, 5-9 = 159.0, 10-14 = 178.0, 15-19 = 138.0, 20-24 = 121.0, 25-29 = 90.0, 30-34 = 140.0, 35-39 = 168.0, 40-44 = 165.0, 45-49 = 232.0, 50-54 = 248.0, 55-59 = 237.0, 60-64 = 178.0, 65-69 = 172.0, 70-74 = 159.0, 75-79 = 79.0, 80-84 = 55.0, 85-89 = 21.0, 90+ = 8.0)
```
Is there any documentation on how this grid was built? The file metadata doesn't point anywhere else but the temporary data repo.

It's pretty easy to write a parser for this, but I need some information on how to translate that to our grid.

**Comment by richardreeve** [comment]
Sorry - I think @soniamitchell is fixing this tomorrow (after the bank holiday) - the data will be a matrix with just the abundances I think with a separate additional 2xN matrix for the x,y location and a vector of (strings?) for the ages.

**Comment by richardreeve** [comment]
I believe that’s now fixed in the temporary_data repo @eperim - see if it makes more sense now? The path in the repo has changed slightly too I’m afraid.

**Comment by claireh93** [comment]
Was just looking at this data briefly, what age categories have the data been binned into for 1k and 10k grids? I can see there are 19 but not what they are, I presume its <5, 5 yearly bins, 90+?

**Comment by soniamitchell** [comment]
Age classes are listed in dataset attributes.

**Comment by soniamitchell** [comment]
I can move them out if this seems unintuitive, but won’t get to it for a day or two.

**Comment by eperim** [comment]
@richardreeve it looks good now. I will write some parsing functions for this soon.

**Comment by eperim** [comment]
MR with functionality here: https://github.com/ScottishCovidResponse/Simulation.jl/pull/41

Still WIP because it needs tests. 

Also, @soniamitchell, when you say "Age classes are listed in dataset attributes", what do you mean? I don't seem to be able to find that in the metadata nor in the file itself (the original `datazone` field has about 90 classes, I couldn't find how they were binned). Am I missing it?

**Comment by soniamitchell** [comment]
The scotland_2018 group should have listed attributes, as should each dataset. In the case of datazone_raw it should have Age Classes, Description, ProcessedWarningScore, and Units. If you’re still having problems finding it let me know and I’ll have a look.

**Comment by eperim** [comment]
When I inspect it here, it seems like `datazone_raw` has the counts for each age for all of the zones:
```julia
julia> size(data["datazone_raw"])
(6976,)

julia> typeof(data["datazone_raw"])
Array{NamedTuple{(:AGE0, :AGE1, :AGE2, :AGE3, :AGE4, :AGE5, :AGE6, :AGE7, :AGE8, :AGE9, :AGE10, :AGE11, :AGE12, :AGE13, :AGE14, :AGE15, :AGE16, :AGE17, :AGE18, :AGE19, :AGE20, :AGE21, :AGE22, :AGE23, :AGE24, :AGE25, :AGE26, :AGE27, :AGE28, :AGE29, :AGE30, :AGE31, :AGE32, :AGE33, :AGE34, :AGE35, :AGE36, :AGE37, :AGE38, :AGE39, :AGE40, :AGE41, :AGE42, :AGE43, :AGE44, :AGE45, :AGE46, :AGE47, :AGE48, :AGE49, :AGE50, :AGE51, :AGE52, :AGE53, :AGE54, :AGE55, :AGE56, :AGE57, :AGE58, :AGE59, :AGE60, :AGE61, :AGE62, :AGE63, :AGE64, :AGE65, :AGE66, :AGE67, :AGE68, :AGE69, :AGE70, :AGE71, :AGE72, :AGE73, :AGE74, :AGE75, :AGE76, :AGE77, :AGE78, :AGE79, :AGE80, :AGE81, :AGE82, :AGE83, :AGE84, :AGE85, :AGE86, :AGE87, :AGE88, :AGE89, Symbol("AGE90+")),NTuple{91,Float64}},1}

julia> data["datazone_raw"][1]
(AGE0 = 3.0, AGE1 = 9.0, AGE2 = 8.0, AGE3 = 9.0, AGE4 = 11.0, AGE5 = 9.0, AGE6 = 10.0, AGE7 = 14.0, AGE8 = 11.0, AGE9 = 11.0, AGE10 = 8.0, AGE11 = 9.0, AGE12 = 11.0, AGE13 = 9.0, AGE14 = 6.0, AGE15 = 7.0, AGE16 = 10.0, AGE17 = 3.0, AGE18 = 4.0, AGE19 = 2.0, AGE20 = 1.0, AGE21 = 6.0, AGE22 = 7.0, AGE23 = 3.0, AGE24 = 6.0, AGE25 = 10.0, AGE26 = 22.0, AGE27 = 13.0, AGE28 = 18.0, AGE29 = 10.0, AGE30 = 9.0, AGE31 = 15.0, AGE32 = 6.0, AGE33 = 24.0, AGE34 = 15.0, AGE35 = 11.0, AGE36 = 20.0, AGE37 = 14.0, AGE38 = 12.0, AGE39 = 11.0, AGE40 = 9.0, AGE41 = 7.0, AGE42 = 10.0, AGE43 = 14.0, AGE44 = 16.0, AGE45 = 15.0, AGE46 = 20.0, AGE47 = 10.0, AGE48 = 14.0, AGE49 = 16.0, AGE50 = 13.0, AGE51 = 6.0, AGE52 = 10.0, AGE53 = 10.0, AGE54 = 17.0, AGE55 = 14.0, AGE56 = 13.0, AGE57 = 8.0, AGE58 = 14.0, AGE59 = 11.0, AGE60 = 16.0, AGE61 = 10.0, AGE62 = 8.0, AGE63 = 15.0, AGE64 = 9.0, AGE65 = 7.0, AGE66 = 11.0, AGE67 = 10.0, AGE68 = 1.0, AGE69 = 11.0, AGE70 = 13.0, AGE71 = 12.0, AGE72 = 6.0, AGE73 = 9.0, AGE74 = 11.0, AGE75 = 7.0, AGE76 = 5.0, AGE77 = 1.0, AGE78 = 3.0, AGE79 = 4.0, AGE80 = 7.0, AGE81 = 4.0, AGE82 = 3.0, AGE83 = 1.0, AGE84 = 1.0, AGE85 = 6.0, AGE86 = 3.0, AGE87 = 1.0, AGE88 = 3.0, AGE89 = 2.0, AGE90+ = 6.0)
```
and the ages there are separated in 90 groups. Maybe I parsed the file wrong and missed some info? This is what I have here:
```julia
julia> data
Dict{String,Any} with 8 entries:
  "grid10k_total"  => [3142.0; 19426.0; … ; 320.0; 79862.0]
  "grid10k_binned" => [167.0 188.0 … 30.0 12.0; 1081.0 1228.0 … 239.0 153.0; … ; 13.0 15.0 … 4.0 2.0; 4586.0 5201.0 … 738.0 343.0]
  "datazone_raw"   => NamedTuple{(:AGE0, :AGE1, :AGE2, :AGE3, :AGE4, :AGE5, :AGE6, :AGE7, :AGE8, :AGE9, :AGE10, :AGE11, :AGE12, :AGE13, :AGE14, :AGE15, :AGE…
  "grid1k_binned"  => [3.0 4.0 … 1.0 0.0; 7.0 8.0 … 2.0 1.0; … ; 17.0 28.0 … 6.0 4.0; 4.0 5.0 … 1.0 1.0]
  "grid1k_id"      => ["616-181", "617-181", "618-181", "619-181", "391-182", "392-182", "393-182", "166-183", "167-183", "631-183"  …  "460-97", "444-95", …
  "grid1k_total"   => [61.0; 136.0; … ; 447.0; 109.0]
  "datazone_id"    => ["S01006506", "S01006507", "S01006508", "S01006509", "S01006510", "S01006511", "S01006512", "S01006513", "S01006514", "S01006515"  …  …
  "grid10k_id"     => ["70-18", "47-19", "48-19", "49-19", "1-19", "24-20", "25-20", "26-20", "66-18", "64-18"  …  "8-12", "9-12", "56-12", "55-12", "54-12"…
```

**Comment by soniamitchell** [comment]
I guess you can't access these data structures using base commands. I suggest you use the HDF5 package (https://github.com/JuliaIO/HDF5.jl). I've had a quick go and it works fine for me. Let me know if you have any further problems.

**Comment by soniamitchell** [comment]
It does however seem like datazone_raw is not a matrix, which was an oversight on my part.

**Comment by eperim** [comment]
I am not using Base commands here's the full snippet:
```julia
julia> using HDF5

julia> rawdata = h5open("/Users/ericperim/Downloads/scrc_demographics1.h5");

julia> names(rawdata)
1-element Array{String,1}:
 "scotland_2018"

julia> data = h5read("/Users/ericperim/Downloads/scrc_demographics1.h5", "scotland_2018")
Dict{String,Any} with 8 entries:
  "grid10k_total"  => [3142.0; 19426.0; … ; 320.0; 79862.0]
  "grid10k_binned" => [167.0 188.0 … 30.0 12.0; 1081.0 1228.0 … 239.0 153.0; … ; 13.0 15.0 … 4.0 2.0; 4586.0 5201.0 … 738.0 343.0]
  "datazone_raw"   => NamedTuple{(:AGE0, :AGE1, :AGE2, :AGE3, :AGE4, :AGE5, :AGE6, :AGE7, :AGE8, :AGE9, :AGE10, :AGE11, :AGE12, :AGE13, :AGE14, :AGE15, :AGE…
  "grid1k_binned"  => [3.0 4.0 … 1.0 0.0; 7.0 8.0 … 2.0 1.0; … ; 17.0 28.0 … 6.0 4.0; 4.0 5.0 … 1.0 1.0]
  "grid1k_id"      => ["616-181", "617-181", "618-181", "619-181", "391-182", "392-182", "393-182", "166-183", "167-183", "631-183"  …  "460-97", "444-95", …
  "grid1k_total"   => [61.0; 136.0; … ; 447.0; 109.0]
  "datazone_id"    => ["S01006506", "S01006507", "S01006508", "S01006509", "S01006510", "S01006511", "S01006512", "S01006513", "S01006514", "S01006515"  …  …
  "grid10k_id"     => ["70-18", "47-19", "48-19", "49-19", "1-19", "24-20", "25-20", "26-20", "66-18", "64-18"  …  "8-12", "9-12", "56-12", "55-12", "54-12"…

julia> size(data["datazone_raw"])
(6976,)

julia> data["datazone_raw"][1]
(AGE0 = 3.0, AGE1 = 9.0, AGE2 = 8.0, AGE3 = 9.0, AGE4 = 11.0, AGE5 = 9.0, AGE6 = 10.0, AGE7 = 14.0, AGE8 = 11.0, AGE9 = 11.0, AGE10 = 8.0, AGE11 = 9.0, AGE12 = 11.0, AGE13 = 9.0, AGE14 = 6.0, AGE15 = 7.0, AGE16 = 10.0, AGE17 = 3.0, AGE18 = 4.0, AGE19 = 2.0, AGE20 = 1.0, AGE21 = 6.0, AGE22 = 7.0, AGE23 = 3.0, AGE24 = 6.0, AGE25 = 10.0, AGE26 = 22.0, AGE27 = 13.0, AGE28 = 18.0, AGE29 = 10.0, AGE30 = 9.0, AGE31 = 15.0, AGE32 = 6.0, AGE33 = 24.0, AGE34 = 15.0, AGE35 = 11.0, AGE36 = 20.0, AGE37 = 14.0, AGE38 = 12.0, AGE39 = 11.0, AGE40 = 9.0, AGE41 = 7.0, AGE42 = 10.0, AGE43 = 14.0, AGE44 = 16.0, AGE45 = 15.0, AGE46 = 20.0, AGE47 = 10.0, AGE48 = 14.0, AGE49 = 16.0, AGE50 = 13.0, AGE51 = 6.0, AGE52 = 10.0, AGE53 = 10.0, AGE54 = 17.0, AGE55 = 14.0, AGE56 = 13.0, AGE57 = 8.0, AGE58 = 14.0, AGE59 = 11.0, AGE60 = 16.0, AGE61 = 10.0, AGE62 = 8.0, AGE63 = 15.0, AGE64 = 9.0, AGE65 = 7.0, AGE66 = 11.0, AGE67 = 10.0, AGE68 = 1.0, AGE69 = 11.0, AGE70 = 13.0, AGE71 = 12.0, AGE72 = 6.0, AGE73 = 9.0, AGE74 = 11.0, AGE75 = 7.0, AGE76 = 5.0, AGE77 = 1.0, AGE78 = 3.0, AGE79 = 4.0, AGE80 = 7.0, AGE81 = 4.0, AGE82 = 3.0, AGE83 = 1.0, AGE84 = 1.0, AGE85 = 6.0, AGE86 = 3.0, AGE87 = 1.0, AGE88 = 3.0, AGE89 = 2.0, AGE90+ = 6.0)

julia> typeof(data["datazone_raw"])
Array{NamedTuple{(:AGE0, :AGE1, :AGE2, :AGE3, :AGE4, :AGE5, :AGE6, :AGE7, :AGE8, :AGE9, :AGE10, :AGE11, :AGE12, :AGE13, :AGE14, :AGE15, :AGE16, :AGE17, :AGE18, :AGE19, :AGE20, :AGE21, :AGE22, :AGE23, :AGE24, :AGE25, :AGE26, :AGE27, :AGE28, :AGE29, :AGE30, :AGE31, :AGE32, :AGE33, :AGE34, :AGE35, :AGE36, :AGE37, :AGE38, :AGE39, :AGE40, :AGE41, :AGE42, :AGE43, :AGE44, :AGE45, :AGE46, :AGE47, :AGE48, :AGE49, :AGE50, :AGE51, :AGE52, :AGE53, :AGE54, :AGE55, :AGE56, :AGE57, :AGE58, :AGE59, :AGE60, :AGE61, :AGE62, :AGE63, :AGE64, :AGE65, :AGE66, :AGE67, :AGE68, :AGE69, :AGE70, :AGE71, :AGE72, :AGE73, :AGE74, :AGE75, :AGE76, :AGE77, :AGE78, :AGE79, :AGE80, :AGE81, :AGE82, :AGE83, :AGE84, :AGE85, :AGE86, :AGE87, :AGE88, :AGE89, Symbol("AGE90+")),NTuple{91,Float64}},1}
```

Am I using the wrong command? That package doesn't really have a lot of documentation. The one command I saw there that mentions attributes doesn't seem particularly useful:
```julia
julia> attr = h5readattr("/Users/ericperim/Downloads/scrc_demographics1.h5", "scotland_2018")
Dict{String,Array{String,1}} with 6 entries:
  "Description"        => ["Population counts for Scottish datazones in 2018. Contains data from ages 0 to 89 in single year increments, as well as 90+."]
  "Source"             => ["National Records Scotland"]
  "datazone_sf"        => ["https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone-boundaries-2011"]
  "SourceWarningScore" => ["0"]
  "datazone_dat"       => ["https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/population/population-estimates/2011-based-spec…
  "DownloadDate"       => ["24/4/20"]
```

**Comment by soniamitchell** [comment]
Ahh.. you're looking at the group attributes, not the dataset attributes. Try `attr = h5readattr("/Users/ericperim/Downloads/scrc_demographics1.h5", "scotland_2018/datazone_raw")`. Also, I've updated the file in temporary_data so that datazone_raw is now a matrix (and `Age classes` start at 0).

**Comment by eperim** [comment]
Oh nice, that certainly returns different data, but still it doesn't seem to show the bins, only the yearly resolution:
```julia
julia> attr = h5readattr("/Users/ericperim/Downloads/scrc_demographics1.h5", "scotland_2018/datazone_raw")
Dict{String,Array{String,1}} with 4 entries:
  "Units"                 => ["datazones"]
  "Description"           => ["population counts (original spatial resolution)"]
  "Age classes"           => ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"  …  "81", "82", "83", "84", "85", "86", "87", "88", "89", "90+"]
  "ProcessedWarningScore" => ["0"]
```

**Comment by soniamitchell** [comment]
The datazone dataset is the original resolution, ages are binned by year. If you need data zones binned by year I can certainly do that. I just put a few example files in there for people to play with. Note that `grid10k_total` and `grid1k_total` are 10k grids and 1k grids respectively, with a single age class (0-90+). Whereas, `grid10k_binned` and `grid1k_binned` are binned into 10 year age groups... I think? (I don't have the file right now)

**Comment by eperim** [comment]
Oh that is exactly what I was wondering. I am just really interested in the gridded data, but I wasn't aware of how those 19 age groups were determined. Are they evenly distributed, then, at every 5 years?

**Comment by soniamitchell** [comment]
They're literally binned into whatever is in the `Age classes` attribute. So `grid10k_binned` and `grid1k_binned` are 0-4, 5-9, 10-14, and so on. These age groups were determined arbitrarily, but I can change the cut offs to anything you like.

**Comment by eperim** [comment]
I don't really have an opinion on how ages should be binned, I just wanted to know what had been the approach taken such that I could encode that in the parsed data. As far as I am concerned, it is 100% now.

**Comment by richardreeve** [comment]
We'll work out down the road how we should be binning ages. I don't think anyone has a real justification for what they're doing right now.
