### ISSUE TITLE
Log spatial location information

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#271]
Related to #270, when we shrink the grid to fit in the data input step, we need a way of tracking where we are in space, i.e. a bounding box of coordinates, for output. Hopefully we should very soon be providing outputs to feed into the other models, so we need to make sure these match up spatially.

**Comment by wytbella** [comment]
In #270 , it mentioned
> and will involve some kind of mapping between the grid id numbers supplied with the data and the x,y position in space,

Is that to say, outside the SImulation.jl model, the geographical information is communicated as `grid id` (both inputs and outputs?). Within SImulation.jl. it should be expressed as `x,y` coordinate?

For this issue #271, do we just want to record the x,y coordinate of the shrink grid, or we want to convert them into `grid id`? What's the format to communicate such information with downstream models? a toml file?

**Comment by sdl1** [comment]
I noticed that `readfile` returns an `AxisArray` with the lat/long info, but then in the example files we always convert this to a plain `Array` before using it. Is there a reason we can't leave it as an `AxisArray` with the spatial information attached?

**Comment by aaron-reeves** [comment]
You may have already thought of this, but could you use British National Grid coordinates for grid IDs (see https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid: I have additional information in the form of C++ code for handling BNG coordinates that could also be useful)?  You could specify, for example, the coordinate of the lower left point of each bounding box (e.g., "NH12341234"), and as long as the bounding box size is known, you'd identify the bounding box and have a system that readily corresponds to other map outputs.

**Comment by claireh93** [comment]
> Is that to say, outside the SImulation.jl model, the geographical information is communicated as `grid id` (both inputs and outputs?). Within SImulation.jl. it should be expressed as `x,y` coordinate?

Yes I believe so, although I need to discuss this a bit more with Sonia, who is processing this data. I think we would need to communicate the coordinates of the output data as `grid id`s for ease of use rather than x,y coordinates. Would we be able to save this as part of a HDF5 file? Say, along with the outputted matrix?

**Comment by claireh93** [comment]
> I noticed that `readfile` returns an `AxisArray` with the lat/long info, but then in the example files we always convert this to a plain `Array` before using it. Is there a reason we can't leave it as an `AxisArray` with the spatial information attached?

It does yes and that's a good point too! I think I was converting it into an array because the main `episode.abundances.matrix` is an integer array rather than AxisArray. But you're right, there's no reason why we couldn't keep this information. Although I think for this new data, the `readfile` function would need to be fairly significantly adapted, as a quick look at the data suggests it is in the format of one long array, with one vector entry per `grid id` containing the abundances of each age category.

**Comment by claireh93** [comment]
> You may have already thought of this, but could you use British National Grid coordinates for grid IDs (see https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid: I have additional information in the form of C++ code for handling BNG coordinates that could also be useful)? You could specify, for example, the coordinate of the lower left point of each bounding box (e.g., "NH12341234"), and as long as the bounding box size is known, you'd identify the bounding box and have a system that readily corresponds to other map outputs.

We hadn't thought about this, but it's good idea @aaron-reeves ! I think we could definitely work towards something like this, although I'll check with Sonia if the `grid id` already refers to something BNG-like.

**Comment by sdl1** [comment]
> I think I was converting it into an array because the main epi.abundances.matrix is an integer array rather than AxisArray

Cool, if we do want to go that way, we can probably generalise the types a bit. It should be possible to do something like
```julia
mutable struct EpiLandscape{T <: AbstractArray{Int}}
  matrix::T
end
```
which should allow `matrix` to be an `AxisArray{Int}`, and still keep things type-inferrable (I think...)

**Comment by claireh93** [comment]
That would be really great! Do you think having an AxisArray as the main matrix would slow things down? Just thinking in terms of accessing and writing data to it in the update loops. Or are they generally similar to using an integer array in that sense?

**Comment by sdl1** [comment]
So I think the theory is it has no runtime overhead over a regular array. However I don't personally have too much experience in this regard, and wouldn't bet on this without trying it out. @wytbella @AlexRobson @eperim any thoughts on this?

**Comment by richardreeve** [comment]
I believe that’s right so long as we’re not iterating using a float or anything (which has to check which element in the array it corresponds to by comparing ranges if I recall from last time I used it)...

**Comment by wytbella** [comment]
@claireh93 @sdl1 , do you want me to relax the constraint and use AxisArray in the same PR dealing with this issue? I assume `EpiLandscape` is the only place that has the constraint? We can quickly benchmark the performance to see whether it causes any significant downside.

In that case, I'll aim to be able to save the output matrix as AsixArray in hdf5. The axis will be long/lat. (If I can figure out how long/la convert to `grid id` and the format is suitable, I'll have the axis as grid id). How does that sound?

**Comment by claireh93** [comment]
Sounds like a good plan @wytbella! From a quick additional chat with Sonia, it sounds like the grid ids are x y coordinates themselves:
> the IDs are [row#]-[column#] (e.g. 1-1, 1-2, 1-3, 2-1, etc.) starting in the bottom left corner

But I believe in future iterations of the data, the x/y should also be provided separately too.

**Comment by claireh93** [comment]
Ah so looking at the data more fully now, it appears as if its only grid ids associated with land, i.e. no sea. So we will need to populate those empty squares separately for a full grid in order to have continuous space. Perhaps, for this issue we focus on testing the axis array performance and storing the spatial locations, still using the old `ScotlandDensity2011.tif` for that. Then, #270 can deal more specifically with how we wrangle the new data into Simulation.jl format?

**Comment by wytbella** [comment]
@claireh93, for the ultimate model output that has the spatial information (e.g. la/long or the coordinates of the shrunk grid), which output parameter/field do you want this information to be embedded?

I now made `epi.epienv.initial_population` to be an AxisArray{<:Int, 2} that carries the la/long or coordinate information? Is that enough? Or do you want to embed such information in other fields in `epi`? Would it be appropriate to use `epi.epienv.names` vector to record such information?

**Comment by richardreeve** [comment]
So long as we can extract it from `epi.epienv.initial_population` I don't think it matters, because we're only using this for export aren't we?
