### ISSUE TITLE
Ensure all outputs including seeds and file paths are written to output logs

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#272]
Ensure the following are included within the output logs for repeats and validation:
- [x] Seed Information
- [x] Location of Parameter Files and Settings Files
- [x] Close issue #245

**Comment by kzscisoft** [comment]
@thibaud-porphyre does this cover all the output you would like?
```
[Parameters File]:
    /home/kristian/UKAEA/SCRC/COVID19_EERAModel/Covid19_EERAModel/data/parameters.ini
[Seed]:
    Type: Fixed
    Value: 1
[Settings]:
    number of parameters tested: 8
...
```

**Comment by thibaud-porphyre** [comment]
@**kzscisoft** if these will be added to the log output files previously create, yes it will cover what we need. cheers
