### ISSUE TITLE
Plan how to deal with the AgeRange class

### ISSUE THREAD

**Issue by aflag** [ScottishCovidResponse/SCRCIssueTracking#273]
A new type, `AgeRange`, was introduced. I intended to extend its usage to the whole code base. However, I want some feedback before implementing it. It will have an impact on how all these structures are accessed: MixingMatrix, the progression dict and the dict of population. Right now, they are all using a string (which is opaque everywhere but in MixingMatrix).

The current implementation (which is to use string everywhere, but parse it in MixingMatrix) turned out to be slower than the previous implementation: from 28s to 44s to run the full simulation in my laptop. The problem stems from `infectionMatrix[a][b]` being slow when doing string-based indexing; as that requires parsing.

The options I thought of moving forward:

### Use AgeRange everywhere

By doing this (and making a small change in the MixingMatrix code) we won't have the issue of parsing the age constantly. Having a strict type as AgeRange rather than a string for age is less suceptible to type errors (or rather, they will show up sooner rather than later). However, since we would not be treating the age groups as opaque strings anymore, changes to that format will require further changes to the code.

I think this is a good option moving forwards, but I'm a bit worried about doing this before we know what the files will actually look like (if age groups are specified in a very different way, we may find ourselves changing things again. Though it will probably be a change in a single class, AgeRange, regardless).

### Keep the opaque string representation

If we don't want to use AgeRange everywhere, but keep the opaque string representation, there are a few options to speed things up:

#### Change access pattern

The code below ends up going through all rows, a column at a time (look at this line in particular: `numInfectiousContactsFromAges[ageInf] = totalInfectious*ageMixingInfectionMatrix[ageInf][age]`). If the access pattern was row based, we wouldn't need to do any indexing, but instead, just iterate over the key, value pairs.

```python
    for age in ageMixingInfectionMatrix:
        newInfectedsByAge[age] = 0

        numSuscept = currentInternalStateDict[(age, 'S')]
        if numSuscept>0:
            numInfectiousContactsFromAges = {}
            totalNewInfectionContacts = 0
            for ageInf in ageMixingInfectionMatrix[age]:
                totalInfectious = currentInternalStateDict[(ageInf, 'I')] + currentInternalStateDict[(ageInf, 'A')]
                numInfectiousContactsFromAges[ageInf] = totalInfectious*ageMixingInfectionMatrix[ageInf][age]
                totalNewInfectionContacts = totalNewInfectionContacts + numInfectiousContactsFromAges[ageInf]
```

#### Create column access methods in MixingMatrix

Another option would be to embrace the column access, by changing how MixingMatrix works. In that case, the code above will still look really similar. It would iterate over keys and values and not do any indexing, but it would still look very much like it does right now.

#### Use string indexing in the infection matrix

This would effectively drop AgeRange from everywhere. I feel the checks it does in the data are relevant, so we would probably still want to those, but done in some other ways.

**Comment by WPettersson** [comment]
I appreciate the thoughts behind this, and I think the option of moving to only using AgeRange makes sense, with the caveat that we don't know what the file format will be yet. With that in mind, do we have any actual problems with running times yet? As in, yes, it has doubled the time taken to run a simulation, but it's still under a minute, so can we hold off on making that decision for a few days, or maybe longer, until we have a better idea of how data might be represented? Or is the running time causing problems, perhaps because we want to run hundreds/thousands of iterations, or try numerous parameters?

**Comment by aflag** [comment]
I don't think it's urgent, but I wanted to raise the issue so that we don't forget. In future, if we are trying to make it run faster, this will be a good place to start.

**Comment by aflag** [comment]
This was delt with in https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/457
