### ISSUE TITLE
Make our tests more robust

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#274]
Some of our tests are very dependent on random numbers, such that small unrelated changes to the code could make the tests fail.  There are three tests which explicitly reseed the RNG to temporarily work around this problem, and there are likely to be others.

Run the tests with a number of different RNG seeds, and update the tests so that they pass most of the time (without explicit reseeding).

**Comment by johnnonweiler** [comment]
There are currently some tests being ignored.  In particular, testMortality is apparently sensitive to the RNG seed.

**Comment by johnnonweiler** [comment]
(Everything else is done, so once those remaining tests are sorted, this issue should be closed.)

**Comment by BlairArchibald** [comment]
Now that testMortality is gone I've not seen any non-robust testing behaviour in a while so I'm closing this!
