### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#275]
Once ScottishCovidResponse/Simulation.jl#37 has been merged, there are going to be some broken tests that we need to understand. We either need to fix them or fix the code, but that PR is not the place to do it I think...

**Comment by richardreeve** [comment]
Blocked until ScottishCovidResponse/Simulation.jl#37 is merged!

**Comment by claireh93** [comment]
Does this still apply @richardreeve? What tests were you thinking of?

**Comment by richardreeve** [comment]
No, the tests now appear to have been fixed.
