### ISSUE TITLE
Implement Covid testing

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#277]
We need a new class and marker to simulate testing for Covid-19. This probably requires a CovidDiagnosticTest Class. The class takes the sensitivity of the diagnostic test as a parameter (default 0.9). 

A proportion of Symptomaticcases (cVirus.getIsSymptomatic()) are tested using the diagnostic test and the person tests positive if rng.get().nextUniform(0.0, 1.0) < sensitivity. The they test negative then they will cease being in quarantine until the case enters Covid phase2

We need a further parameter to determing whether the person gets a test. 50% of adults and pensioners that show symptoms get tested.

**Comment by BlairArchibald** [comment]
Merged in ad11e46
