### ISSUE TITLE
Write location of infection to file

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#279]
We want to write the location that each case was infected to a file. The csv should take the format:
Iter, Day, Cases_household, Cases_Neighbours, Cases_Restaurant, Cases_Shops, Cases_Nirsery...

**Comment by BlairArchibald** [comment]
Believe this is possible in the current output format:

"iter,day,H,L,A,P1,P2,D,R,ICs,IHos,INur,IOff,IRes,ISch,ISho,IHome,IAdu,IPen,IChi,Iinf,DAdul,DPen,Dchi,Dinf"

Where ICs = Cases_constructionSite, IHos = Cases_hospital, etc.

Is this what's required?

Note: These are daily statistics, not cummulative.

**Comment by paulbessell** [comment]
Good lord. So it is. Soryr I missed that. Issues easily resolved
