### ISSUE TITLE
Person age and sex from data file

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#280]
Generate individuals of age and sex using the supplied data file. The ages and sexes are in brackets, but can be spread evenly across the bracket to generate a unique integer age for each person.

Tags of Infant (<5yrs) Child (<18yrs) Adult (<65 yrs) and Pensioner can then be assigned.

**Comment by johnnonweiler** [comment]
@BlairArchibald I'm assigning you to this because I think you've already started working on it.

**Comment by BlairArchibald** [comment]
Merged in 6af1cdf
