### ISSUE TITLE
Fix bug in sampleUseOfModel that sums numbers of people in compartments over multiple trials

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#283]

**Comment by aflag** [comment]
@magicicada when you raised this bug, did you run this version of the sampleUseOfModel? https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/simple_network_sim/sampleUseOfModel.py I thought that, by always resetting network.states[0] this problem wouldn't happen anymore.

**Comment by magicicada** [comment]
I think it did (for all but the first time step, at least), but I could be wrong - an easy way to check is to seed the epidemic at the same place in each trial and the look at or plot them all, they should all be the same rather than increasing.
