### ISSUE TITLE
Adapt simulation to use dynamic dampening of network movements over time

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#285]
If possible can this be optional?  That is, if no dampening information is specified, operate at full volume for the whole sim

**Comment by bobturneruk** [comment]
"Damping" in this context is a time dependant proportional modifier (between 0 and 1?) applied to the rate of movement between network nodes. This simulates the effect of policy on changing how many people are moving around the network.
