### ISSUE TITLE
Adapt simulation to use dynamic dampening of within-node contacts over time

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#287]
Apologies - I just archived this issue accidentally and can't figure out how to get it back, so sorry if this is a duplicate!

This is the within-node analogue to the dampening of network movements.

**Comment by aflag** [comment]
From the closed duplicate:

> Read time-dependent dampening factor for the age-mixing within-population contacts and then apply to the within-population contacts (and thus eventually to the resulting infection). This is similar to what we've done with the movement dampening.
