### ISSUE TITLE
Shrink grid to fit.

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#3]
At the moment uses a dense matrix for spatial discretisation. The sea is marked by inactive cells, land cells are marked active. The sea cells are a waste of computational effort (although minimal) but represent a bottleneck in parallelisation via domain decomposition. We need to work out how to remove need of inactive cells.

Needs to be done in 2 stages:

1. Make the grid tightly bound - all edges have at least one active cells
2. Figure out how to remove inactive cells e.g. via sparsity

**Comment by jwscook** [comment]
Need to look in:

https://github.com/ScottishCovidResponse/Simulation.jl/blob/epi/src/Epidemiology/EpiEnv.jl
https://github.com/ScottishCovidResponse/Simulation.jl/blob/epi/src/Epidemiology/EpiLandscape.jl
https://github.com/ScottishCovidResponse/Simulation.jl/blob/epi/src/Epidemiology/EpiSystem.jl
https://github.com/ScottishCovidResponse/Simulation.jl/blob/epi/src/Epidemiology/EpiGenerate.jl

**Comment by jwscook** [comment]
Example https://github.com/ScottishCovidResponse/Simulation.jl/blob/epi/examples/Epidemiology/Scotland_SIR_example.jl lines 19 to 26

**Comment by jwscook** [comment]
Links with #10

**Comment by sdl1** [comment]
Planning to do
> 1. Make the grid tightly bound - all edges have at least one active cells

in the appropriate constructor, this should at least reduce the number of inactive cells

**Comment by claireh93** [comment]
Closed with ScottishCovidResponse/Simulation.jl#32
