### ISSUE TITLE
Amend compartmental model to match central consortium plan.

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#307]
SCRC has identified a common compartmental model that is a little different than what we have been using.  We've been asked to amend our models so that running with that new structure is at least an option.  In addition to changing the transitions, this will also need us to change the defs of what is considered "infectious".  I suggest we start passing a list of states that are considered infectious to the basicSimulation function as a parameter - @aflag Any thoughts?

**Comment by aflag** [comment]
Sounds good, in the changes I was doing this morning I actually had this: 

```
SUSCEPTIBLE_STATE = "S"
EXPOSED_STATE = "E"
INFECTIOUS_STATES = ["I", "A"]
```

We can easily make that a parameter of the basicSimulation function

**Comment by WPettersson** [comment]
For forward compatibility, may I suggest
```
SUSCEPTIBLE_STATES = ["S"]
EXPOSED_STATES = ["E"]
INFECTIOUS_STATES = ["I", "A"]
```
It makes things more consistent, and also makes it trivial to support any further changes.

**Comment by bobturneruk** [comment]
Need agreement on compartment names at SCRC.
