### ISSUE TITLE
Abundance data output

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#309]
Following on from #271, we now need to output the model with spatial information in HDF5 format, in order to process and input into other models. We discussed outputting abundances along with information on compartment, spatial grid location and time (which may be stored as metadata?). Initially, working on current model structure but may eventually incorporate AxisArray developments from #281

**Comment by sdl1** [comment]
One thing we might want to think about here is outputting data as we go at each time step. (Not sure if there's a way of appending into hdf5 files? If not we could just output a separate file and then maybe join them at the end.) This would remove the need for pre-allocating a very large output matrix as is currently done, which is probably not scalable?

**Comment by richardreeve** [comment]
Yes, that's a great idea, and there's no problem at all with it. In fact, now you mention it, I believe HDF5 is specifically designed to do this so it can easily record exactly this kind of large time series data. There's a bit on writing in chunks here - https://github.com/JuliaIO/HDF5.jl/blob/master/doc/hdf5.md - which I think may be the right approach, but there may be better docs elsewhere.

In fact, now I think about it, it may even be possible to write to the correct spatial chunks from each node in the MPI version of the code, which would be a particularly cool way of saving out stuff to a single file without wasting bandwidth assembling the data centrally... maybe?

**Comment by richardreeve** [comment]
Fixing this would make ScottishCovidResponse/Simulation.jl#41 usable, so it would be fantastic to get this incremental storage working asap.
