### ISSUE TITLE
Store force of infection as well as environmental virus

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#311]
Currently force of infection is recorded in the cache, which is zeroed out at the end of every grid step. This should also be stored in `epi.abundances.matrix_v` (and overwritten each time) and the number of virus categories extended to two.

**Comment by wytbella** [comment]
A couple of questions

> Currently force of infection is recorded in the cache

Do you mean `beta_force` and `beta_env`?

> , which is zeroed out at the end of every grid step

What do you mean by `grid step`? Could you link the corresponding parts of the code?

> This should also be stored in `epi.abundances.matrix_v` (and overwritten each time) and the number of virus categories extended to two

What shape/size do you expect `epi.abundances.matrix_v` to be ultimately? It's now a matrix of size `1*num_grid_id`.The "two virus categories" are virus in the `air` and virus in the `environment reservoir`? Are the values representing the amount of virus in one grid_id cell?

**Comment by claireh93** [comment]
Hi Bella, 

> Do you mean beta_force and beta_env?

Not directly, these are the parameters that control how much transmission occurs from each viral population. I was thinking more of the `epi.abundances.matrix_v` created in EpiLandscape.jl. At the moment, I have one virus category in here (the `environment reservoir`) and the force of infection is instead stored in the `epi.cache`, which is zero'd out at the end of the timestep: https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/src/Epidemiology/EpiGenerate.jl#L68

> What shape/size do you expect epi.abundances.matrix_v to be ultimately? It's now a matrix of size 1*num_grid_id.

Instead I would like to store it in `epi.abundances.matrix_v` - so this becomes a matrix of size `2*num_grid_id`. However, the force of infection disappears at the end of each timestep so this would probably involve making sure this entry of the matrix is overwritten each time. We will also need to extend the number of virus classes in the examples/tests, e.g. https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/test/canonical/test_age.jl#L13.

>The "two virus categories" are virus in the air and virus in the environment reservoir?  Are the values representing the amount of virus in one grid_id cell?

Yes to both, and it would be good to have them named explicitly in the `EpiList`, under `epi.epilist.virus.names`.

>What do you mean by grid step? Could you link the corresponding parts of the code?

Oops sorry, I meant timestep here! So each step of the model.

**Comment by wytbella** [comment]
Thanks @claireh93! I probably need a bit epidemiology 101 here :-p

> I have one virus category in here (the `environment reservoir`) and the force of infection is instead stored in the `epi.cache`.

What does "force of infection" mean in terms of viral population? Currently the value stored in `epi.abundances.matrix_v` is the viral population in `environment reservoir`, which is calculated as `virus(epi.abundances)[1, :] .+= (nm .+ vm)`.  Is the `vm` or `epi.cache.virusmigration` here you want me to store in `epi.abundances.matrix_v[2,;]` (according to [this](https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/src/Epidemiology/EpiGenerate.jl#L68)?  What's the reasoning behind it? `vm` is the "new born" virus at a time step, right? Then if you sum `epi.abundances.matrix_v` over the first dimension (virus compartment), it's not the total amount of virus, right? I don't understand why the new born virus is a separate entry in `epi.abundances.matrix_v`.

>Yes to both, and it would be good to have them named explicitly in the EpiList, under epi.epilist.virus.names.

Naming is hard, could you tell me what these 2 categories should be called?

> However, the force of infection disappears at the end of each timestep so this would probably involve making sure this entry of the matrix is overwritten each time. 

Do you mean you want `vm` to be recorded in `epi.abundances.matrix_v[2,:]`, not the "cumulative sum of `vm` over timestep"?

> We will also need to extend the number of virus classes in the examples/tests, e.g. https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/test/canonical/test_age.jl#L13.

Does that apply to all files in `test/canonical/`? any other tests that need to update?

**Comment by claireh93** [comment]
Sorry for the late response @wytbella! 

>What does "force of infection" mean in terms of viral population?

In this model force of infection is generated by the infectious human categories and distributed over space according to the kernel in `virusmove!`, referred to as `vm`. We are assuming that this force lands on the ground and adds to the environment reservoir, which slowly decays over time (referred to here as `vm .+ nm`). We will want to store the force as the instantaneous count at each timestep, assuming it is wiped out in between.

> Do you mean you want vm to be recorded in epi.abundances.matrix_v[2,:], not the "cumulative sum of vm over timestep"?

Yes exactly, I think the major change here is that instead of `epi.cache.virusmigration[1, :] .+= vm` we should have something like `epi.abundances.matrix_v[2, :] += vm`. Then things will also need to change further on in the `classupdate!` loop at https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/src/Epidemiology/EpiGenerate.jl#L110 to reflect the new storage

> Naming is hard, could you tell me what these 2 categories should be called?

Sure, probably to start with we could have `force` and `environment`- might need to change, but at least that can allow us to delineate between them for now.

> Does that apply to all files in test/canonical/? any other tests that need to update?

Yes it will and TestCases.jl (along with maybe some others like test_EpiGenerate.jl), as well as the examples too. Hopefully that makes sense (I'm not sure how clearly I have managed to describe things here), but I'm happy to have a quick video chat about it if that would help too.
