### ISSUE TITLE
Model hospitalization

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#314]
We probably don't want to do this yet, because it is level of complexity too far for now.

**Comment by paulbessell** [comment]
There is a test in place for ovement to Hospital

**Comment by BlairArchibald** [comment]
Initial hospitalisation was merged in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/85

I'm closing this since we have other issues to handle the changes we still want to add.
