### ISSUE TITLE
Update tests in pbverify branch

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#316]
Some of the unit tests in the pbverify branch are now obsolete. Could you please take a look at them Bob.

**Comment by johnnonweiler** [comment]
@bobtaylor12 - I think you already did this.  Can I close this issue?

**Comment by bobtaylor12** [comment]
Yes, that's fine.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
