### ISSUE TITLE
Automatically estimating and outputting R

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#320]
Right. Bare with me on this. For the initial period of the epidemic we want to estimate R and this is a method that may get more involved. R is this number that people are banging on about on the TV and wireless and stuff. What it describes is if an indovidual gets infected then how many will they go on to infect. There are clever empricial ways of estimating this, but we know who infected who, so let's just calculate it.

So, for each infected person we want to create a log of the day & time that the person was infected, the number of people that they infected and the day & time that they infected each secondary.

Then and the end of each simulation:

1. I want to output to a file and log on the logger the mean R for the initial phase of the epidemic, for the time being we will define the initial period as the first 5% to become infected, or the period befor elockdown (whichever is reached first). The mean R is the mean number of secondaries that were caused by each person infected in that initial period. I also want the mean generation time, here generation time is the time from infection of the primary case to the secondary case, so if I am infected on day 5 and I infect somebody else on day 15 then generation tiem is 10 days
2. In the main output file we add for each epidemic day the mean R and mean generation time for people infected on that day. So this is the R and generation time that are specific for that day. If no persons are infected on that day then leave blank please

**Comment by BlairArchibald** [comment]
I'm adding in some infection logging features for handling testing, so I'll probably add a bunch of stuff related to this there.

**Comment by BlairArchibald** [comment]
Merged in  3c6c8
