### ISSUE TITLE
Ratio of Households to Population

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#322]
At the moment the model takes a population and a number of households as model arguments. By default we use 10,000 populaiton and 3,000 households (ratio = 3.33.). A more accurate ratio would be 2.18 (4,587 households), but this breaks the model.

Instead of giving it a population as a model argument (as we do now) but a ratio of population/hosuseholds as an argument in the population parameters (with a default of 2.18 and make it so that we can populate households with this ratio.

**Comment by paulbessell** [comment]
Blair, I assigned oyu as you know your way round that neighbourhood of the code, but feel free to tell me to go away if you have enough to do already.

**Comment by BlairArchibald** [comment]
Merged in 7c7bbbd
