### ISSUE TITLE
`test_run_seeded` fails on Windows 10

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#323]
https://github.com/ScottishCovidResponse/simple_network_sim/blob/732e7c3a4bd8081243b105b266bf6b2ab593c886/tests/regression/test_sampleUseOfModel.py#L8

Hashes are not the same - obviously runs on Linux or CI wouldn't pass!

**Comment by alex-konovalov** [comment]
Maybe we can investigate possibilities of using AppVeyor for running CI tests under Windows.

**Comment by bobturneruk** [comment]
Thanks @alex-konovalov ! 

Weirdly, the only reason to run on Windows that I'm aware of at the moment is that I use it for development. This I can do in a Linux VM if it makes life easy! `simple network sim` only really *needs* to work in the [tightly spec'd conda environment](https://github.com/ScottishCovidResponse/simple_network_sim/blob/master/spec-file.txt) we use in the CI, as this is what will be used when we're generating outputs to feed into the data pipeline and on to visualisation.
