### ISSUE TITLE
Create abstract interface to random number generator

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#333]
Many parts of the code base use outputs from the GSL random number generators. It is difficult to test these properly without either:
* using a fixed randomiser seed
* or using link substitution to swap out the randomiser.
Both of the above have problems.

A better solution is to develop an abstract interface to the randomiser, which would allow us to use dependency injection in cases where a random number generator is required. Further, it would then be easy to develop Mocks which could be used in tests in place of the generator.

**Comment by thibaud-porphyre** [comment]
sorry, I am not clear what you are proposing. Do you want to fix parameters for testing purposes only?

**Comment by peter-t-fox** [comment]
Essentially yes, but I appreciate that it sounds a bit vague. It should become clearer when I've done it.
