### ISSUE TITLE
Check reason for NaN check

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#334]
The function `parameter_select` has the following chunk of code:

```
double tmpval = perturbList.parameter_set[xx]+vlimitKernel[xx]*gsl_ran_flat(r, -1, 1);
while(std::isnan(tmpval) || tmpval<=vect_min[xx] || tmpval>=vect_Max[xx]){
        	tmpval = perturbList.parameter_set[xx]+vlimitKernel[xx]*gsl_ran_flat(r, -1, 1);
        }
```

It is not clear why the check `std::isnan` is done? It should be possible to remove it.

**Comment by thibaud-porphyre** [comment]
theoretically, it should be removed. However, this is a check to make sure that only numbers are return. In the past use of this framework, this was actually needed as it depends on the parameter and (its distribution) you are sampling.
