### ISSUE TITLE
Clang-tidy dumps all of its output to screen

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#340]
As a result of #339, a build now produces an enormous number of warnings onto the screen. Until we assign someone to specifically address the warnings and establish which ones actually matter, the output should be disabled. Otherwise it's a distraction, and may hide more serious warnings caught by the compiler.

**Comment by kzscisoft** [comment]
Addressed in https://github.com/ScottishCovidResponse/Covid19_EERAModel/pull/34
