### ISSUE TITLE
Switch to using portable C++ RNG to avoid dependence on C library (e.g. macOS vs Linux)

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#363]

**Comment by rwj11** [comment]
This could use the standard C++11 facilities in the <random> header, which should have better statistical properties than some rand() implementations.
At present, different srand() seeds are set on different tasks (in analysis.cc, MBP.cc and PMCMC.cc), so these calls will need be modified as well as calls to rand().  The could be replicated using std::seed_seq, but see also comment by @ianhinder above.

**Comment by ianhinder** [comment]
The comment about results being independent of parallelisation refers to the PMCMC method, which is really parallelising a task which could be done in serial. This method is going to be removed from the code because it's becoming too much of a maintenance burden.  The MBP method is different; the only difference between the processes is the random seed, so there is no concept of parallelising a task and needing the results to be the same. Probably we just need to set a different seed on each rank, as is presumably done now.

**Comment by ianhinder** [comment]
What do you mean by "standard C++11 facilities in the header"?

**Comment by rwj11** [comment]
I think that &lt;random&gt; may have been edited out of my comment because it looked like HTML!

**Comment by ianhinder** [comment]
ah yes! you need a leading backslash on the first less-than.  you can click on "Preview" above the comment box to see what it's going to look like. comments in github are in markdown, so html is interpreted as html.  github then sanitises it to remove most html, but there you go 🙂 

yes, my plan would have been to use the RNGs in  \<random>. when I did an initial search, my conclusion was that at least some of them are guaranteed to be portable. perhaps consider the [Mersenne Twister](http://www.cplusplus.com/reference/random/mersenne_twister_engine/) (after checking to make sure it's supposed to be portable). we probably only realistically care about Linux and macOS at this point, so we should test on those.

**Comment by rwj11** [comment]
OK, I'll look at this case too.
Some of the tickets could give a little more detail on how to reproduce the behaviour...

**Comment by ianhinder** [comment]
Sorry about that 🙂 They were probably written in a few seconds to jog my memory.  Ping me if you want to look at one of them and I'll give more details.

**Comment by ianhinder** [comment]
See https://github.com/ScottishCovidResponse/BEEPmbp/pull/11.

**Comment by ianhinder** [comment]
I've merged the implementation from PR11 into dev, but disabled it in the Makefile.

@chrispooley: we have a new random number generator which should be portable across platforms, and has a much better reputation than "rand". It's the Mersenne Twister RNG, which is traditionally applied to MCMC simulations.  You can enable it in the Makefile by removing -D OLD_RAND from CPPFLAGS.  Since the RNG is such a critical piece of the algorithm, I don't want to enable it unless you're happy with it.  It will give different results to rand(), but the "randomness" should be better.  Is there anything we or you should check before enabling it by default?  Maybe some of the checks from 
https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/365?

**Comment by ianhinder** [comment]
I've checked that the new RNG gives the same sequence of random numbers with gcc and clang, so we're improving!  We can set it as the default if Chris is happy to do so, or after any additional checks he thinks we should perform.

**Comment by chrispooley** [comment]
I am happy with this if you think it is a sufficiently good random number generator.

**Comment by ianhinder** [comment]
I've changed the default to use the new RNG.
