### ISSUE TITLE
Clean up input and output for simulation and inference runs

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#380]
Currently cases, houses and events are written to the current directory by the simulation run.

**Comment by ianhinder** [comment]
Need to check whether this is still the case.

**Comment by ianhinder** [comment]
Currently, when run in simulation mode, the code reads some input data from "datadir", and then writes some of its results back into datadir (those that are likely to be wanted for future inference), and some results into outputdir (these appear to be posteriors, which looks wrong; I've asked Chris about this). 

I think all output should go into the outputdir, and should not be mixed with input data. Apart from just being a general good practice, this would allow you, for example, to run multiple simulations at the same time without them overwriting each others' output files.  This would be a straightforward change, but it makes it harder to then run inference on the simulated data, because you would have to copy the simulation output into the same directory as other input data. 

The files written into the data directory by simulation appear to be the transitions, and the populations in each compartments. I think there are two options:
1. Add a new parameter, e.g. transpopdatadir, which would be a directory to look for this data in first, and if it's not found there, it would look in datadir. You would then set transpopdatadir to the Output directory of a simulation if you wanted to run on simulated data.  OR
2. Allow multiple datadirs to be specified; when a file is looked for, it will be taken from the first datadir in which it is found.

Note that some of this might become moot when we integrate with the data pipeline.  Maybe before implementing either of the above, we should start integrating the sort of interface we will need for the data pipeline, to see if there is a more natural fix in that context.

**Comment by ianhinder** [comment]
This seems to have all been sorted out now. Transition data is read from the data directory, and if it's not found, it's then read from the output directory. The assumption is that if you run a simulation, you then run inference in the same output directory. It's a bit ugly, but it works. If you wanted to run multiple inference runs on the same simulated data, you would need to copy it somewhere else.  Also, if you had a data directory containing simulated data, there's no way to force it to look in the output directory first. Actually, maybe the output directory should be checked first. @chrispooley : would it make sense to look first in the output directory, and only if the file is not found there, to look in the data directory? If so, I can make that change.

**Comment by chrispooley** [comment]
You can change it if you think it is better. For me most users of this software would be analysing there own data. The simulation then inference is just something we do as a diagnostic check.

**Comment by ianhinder** [comment]
This has now been implemented.
