### ISSUE TITLE
Exclude emsg and ran from doxygen call trees

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#385]
These functions are called from large numbers of places and make the call trees very cluttered.

**Comment by ianhinder** [comment]
See http://doxygen.10944.n7.nabble.com/Call-Graphs-excluding-functions-td4660.html.

**Comment by rwj11** [comment]
See also https://www.doxygen.nl/manual/commands.html#cmdcond
I wonder whether excluding `ran()` is actually a good thing -- it seems potentially useful to know exactly where the stochasticity enters the system.

**Comment by ianhinder** [comment]
Thanks for the link to cmdcond. Yes - it's useful to have, but it makes it very cluttered. Depends what is more important.

**Comment by ianhinder** [comment]
This is the current call graph starting from main.
![image](https://user-images.githubusercontent.com/213274/87581956-a6f8a900-c6d1-11ea-849b-4516015d9f75.png)
I think it would make sense to exclude emsg but not ran.

**Comment by ianhinder** [comment]
Much better:
![image](https://user-images.githubusercontent.com/213274/87582471-55045300-c6d2-11ea-88e9-11cb447165e0.png)

**Comment by ianhinder** [comment]
Implemented in https://github.com/ScottishCovidResponse/BEEPmbp/commit/e05f6342e26c63ea79fd40e5ecc4085d6665c157.

**Comment by ianhinder** [comment]
@rwj11  I'm very sorry, I hadn't noticed that you assigned it to yourself an hour before I worked on it. I should have assigned it to myself, at which point I would have noticed. I'll try to remember to assign thing before working on them!
