### ISSUE TITLE
Non-portable use of variable-length arrays

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#400]
There are a number of places in the code where variable-length arrays are declared e.g.
```
	double seed_pop[n_agegroup-1];
```
Variable-length arrays are not part of the C++ standard: they are a C99 feature. GCC supports them in C++ as an extension, but this renders the code non-portable. See e.g. https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard and http://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

All variable-length arrays should be replaced with vectors. In cases where a raw C-style array is required (e.g. for a call to the GSL), an array can be extracted from a vector by a call to the `data()` member function (https://en.cppreference.com/w/cpp/container/vector/data).

Examples:
- [ ] `GenerateDiseasedPopulation line 464
```
unsigned int startdist[seedarray.size()];
```

**Comment by kzscisoft** [comment]
@peter-t-fox I think I have addressed this in `kzscisoft/run-restructure` as I now use `std::vector`, the seed array is now generated by a function that returns this type.
