### ISSUE TITLE
Unclear convention for regression test reference outputs

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#402]
When the code runs, the output files are timestamped with the time of the model run as part of the file name e.g. `output_abc-smc_ends_step0_shb15_06-06-2020_09-33-47.txt`.

However, the contents of the regression test reference output directories do **not** have the timestamps in the file names. This is true even on branch https://github.com/ScottishCovidResponse/Covid19_EERAModel/tree/kzscisoft/SCRC-379, which recently updated the regression test outputs. 
How was this done? Were the timestamps removed manually?

**Comment by kzscisoft** [comment]
@peter-t-fox I do not think this is a bug, I did mention this on Zulip although I believe my exact words were "bash magic", the lines you are looking for are in the bash script `scripts/CheckRunOutputs.sh`:
```
filename=$(basename $expected_filepath)
filename="${filename%.*}"
actual_filepath=$(find $ACTUAL_OUTPUTS_DIR -name "${filename}*")
actual_filepath=${ACTUAL_OUTPUTS_DIR}/$(basename $actual_filepath)
```
