### ISSUE TITLE
Documentation of Code and Doxygen/Repository Website

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#407]
The following objectives should help improve documentation/understanding of the code:

- [ ] Docstrings/comments should be added to all functions. Any sections of code which would be difficult to interpret by an outside user should also be accompanied with comments to help. All variables should be accompanied (where possible) with descriptions.
- [x] Doxygen website displaying the resulting documentation generated by running `doxygen` within the repository. This site will be hosted via GitHub Pages on the `gh-pages` branch which should not be deleted. Currently the main `index.html` forwards to `doxygen/html/index.html` in this branch.
- [x] Coverage reports displayed on website. The coverage reports generated by `lcov` should also be displayed on the website. This means editing the main `index.html` file to instead display a menu where you can choose to go to the Doxygen documentation or the coverage pages.
- [x] Add Clang Tidy information to the site for easy reference later.
- [x] Add CppCheck information to the site.
- [x] Add automatic code formatting using `clang-format`

**Comment by peter-t-fox** [comment]
Closing this as the actionable things have been achieved. The general point about writing API documentation for functions, classes, etc. will remain true, but this is covered by the code review process in general.
