### ISSUE TITLE
Wrap all code in examples in functions

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#408]
Currently at least one example has it's variables in global scope, which is not ideal for performance. The examples should be wrapped in functions which are then called within the file itself.

e.g.

```julia
using Simulation
x = EpiSomethingOrOther() # in global scope
do_operations_from_Simulation(x)
```

should go to:

```julia
using Simulation
function run()
  x = EpiSomethingOrOther() # no longer in global scope
  do_operations_from_Simulation(x)
end
run()
```

**Comment by AlexRobson** [comment]
Think that this one is quite important (and I was planning on something similar myself), and beyond just performance reasons. If we want to pass some parameter specification for a particular experiments, this will be required. 

Then, we can do something like (psuedocode)

```
params = getparameters(...)
results1 = experiment(params...)

params = getparameters(...)
results2 = experiment(params...)
```

Probably also needed for any inference/parameter search.

**Comment by richardreeve** [comment]
Actually, I was wondering whether we should be reading in parameters from files via the data API like everything else. The model will have its own part of the namespace, `simulation.jl/params/...` or something, with a specific name for each input I guess, and we'll have to work out a way of aliasing or versioning to get different values or something?

We can put them into a run script, but the problem with that is that we'll either have to have lots of them or we'll have to keep going back and forth through the git history. On the other hand, if we can keep it in the data repository, we can search the repo for all of the runs where we used this setting, for instance...
