### ISSUE TITLE
Consider removing `simplified_age_infection_matrix.csv` and change references to target `simplified_age_infection_matrix_from_comix.csv`

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#423]
`simplified_age_infection_matrix_from_comix.csv` may supersede `simplified_age_infection_matrix.csv`

**Comment by FiodorG** [comment]
Superseeded by https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/523
