### ISSUE TITLE
Change lockdown parameters

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#429]
So at the moment lockdonw closes down everything and reopens everything at the same time, with a dirty old fudge around schools. The current closing of everything is fine, but it would be useful if we could do a more graduated release from lockdown - sector by sector and posisbly in a more restricted way - such that we could define people contacting fewer neighbours and small numbers returning to wokr at offices. Also if we could think about how to age structure these.

**Comment by BlairArchibald** [comment]
I think this is all covered with the recent lockdown changes. We can re-open if not.
