### ISSUE TITLE
Add input file to setup all parameters

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#43]
Move all the hardcoded parameters into an input file (or two - consider separating out epidemiological parameters from run configuration/options).

There are already some classes for reading json input, taken from the Contact-Tracing-Model project, which already uses some input files in this way.

**Comment by johnnonweiler** [comment]
I think @sam-brett may be doing this at the same time as the "cleanup first steps".

**Comment by johnnonweiler** [comment]
Review (in particular) any code marked 'bodge' or 'fudge' - these are mostly about where we need to use good parameters.

**Comment by BlairArchibald** [comment]
Merged in 55fad4412d211a6e994f681d5ccad175bf875a59
