### ISSUE TITLE
Create care homes

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#433]
Care Homes

These are going to extend Place(). 

In terms of parameters:
            "populationToCareHomesRatio":5000,
            "CareHomesSizeDistribution":{
                "pSmall":0,
                "pMed":1,
                "pLarge":0
            },

      "workerDistribution":{"pHospital":0.15 //(we will reduce Hospital workers to make room for care home workers  
"pCareHome":0.01}

The workers will do four shifts:
6-14; 14-22 Days 1-3; Days 4-7

**Comment by johnnonweiler** [comment]
How does this relate to #182 ?

**Comment by BlairArchibald** [comment]
I'll pick up the set of Care Home changes

**Comment by BlairArchibald** [comment]
Merged in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/94
