### ISSUE TITLE
Populate care homes. Continues #433

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#434]
So for each person over 70 years of age there is a probability of 0.045 that he/she will be a Care Home resident.

What I suggest is that we allocate them to a Household and then they are on secondment to the the Care Home but that they do not leave. to go to shops, restaurants or visit neighbours. Unpleasant to think of though it is, it is reasonable to assume that they will not have visitors.

**Comment by BlairArchibald** [comment]
Merged in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/94
