### ISSUE TITLE
Implement Covid in Care Homes. Continues #434

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#435]
The grim bit. And the more complicated bit

We will specify:
  ```
      "buildingProperties":{
           "CareHomeTransmissionConstant":10.0,
} 
```

Before the Care Home resident becomes Symptomatic we will treat transmisison in the Care Home as we do any other Place().

Once the patient becomes Symptomatic they are quarantined in the Care Home and only contact Care Home workers. Transmisison is the same as Symptomatic patients in Hospital with 
                                                                      `transP *= CovidParameters.get().hospitalisationParameters.hospitalisationTransmissionReduction;`
This is essentially a PPE adjustment.

Covid cases in Care Homes **never** go to Hospital.

**Comment by paulbessell** [comment]
We also need to record deaths in Care homes separate form deaths at home

**Comment by BlairArchibald** [comment]
Merged in https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/94
