### ISSUE TITLE
Add EERA parameters to temporary_data repo as staging for data registry

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#444]
The [temporary_data](https://github.com/ScottishCovidResponse/temporary_data) repo needs to be populated with the inputs for the Covid19_EERAModel model so that they can be read in using the data pipeline API. For the time being they should be stored in a `temporary/Covid19_EERAModel/...` path - we can easily move them later. The initial focus is the actual parameters and distributions that can be written as text and stored in the repo. We do now have an ftp site to store the hdf5 files, but we'll come to them next. This is a link to the parameters (on Teams) that need to be put into the repo - https://teams.microsoft.com/_#/school/files/General?threadId=19%3A283c5ea4551344249cc76dd0ecaa4f74%40thread.tacv2&ctx=channel&context=Covid19_EERAModel&rootfolder=%252Fsites%252FScottishCOVID-19ResearchConsortium%252FShared%2520Documents%252FGeneral%252FCollaboration%252Fmodel-parameters%252FCovid19_EERAModel - this is a folder in General called Collaboration -> model-parameters -> Covid19_EERAModel in case the link doesn't work (it doesn't for me!).

**Comment by richardreeve** [comment]
There is a description of what the files currently ought to look like in a wiki in the SCRC-internal repo: https://github.com/ScottishCovidResponse/SCRC-internal/wiki/Model-data-pipeline-API-specification

**Comment by peter-t-fox** [comment]
Closing this as the relevant repository is now deprecated. EERA model data has been populated on the registry and the FTP/DataRepository locations.
