### ISSUE TITLE
School holidays

### ISSUE THREAD

**Issue by paulbessell** [ScottishCovidResponse/SCRCIssueTracking#447]
Quite a lot of transmisison is at schools, so could we please pop a half term holiday in there. Days 28-32 kids don't go to school

**Comment by johnnonweiler** [comment]
I wonder what the best way is to encode this in the parameters file.  Perhaps a list of days?

**Comment by paulbessell** [comment]
For now we only need one half term holiday, Let's start just having a start and end day for this holiday. When more detailed questions come in about school reopening we will need to add lots of scenario specific details then. So for now I suggest just doing the one holiday that happenned and worry about the remainder in the future when we do that modelling

**Comment by BlairArchibald** [comment]
As a thought, perhaps we should introduce a DateRange type, since this can also be used for lockdowns etc. Holidays can then be a list of date ranges (or a single one for now)?

**Comment by paulbessell** [comment]
> As a thought, perhaps we should introduce a DateRange type, since this can also be used for lockdowns etc. Holidays can then be a list of date ranges (or a single one for now)?

Not entirely sure what this means, but it sounds like a generally wise idea.
