### ISSUE TITLE
Write scripts to extract data from source (extractors) for upload to pipeline

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#458]
Some of the input data is transformed from it's source prior to being used by simple network sim. These transformations should be recorded somewhere, or implemented in our code.

**Comment by magicicada** [comment]
As an example, I've hunted down and listed the steps taken to generate the more realistic movement multipliers that Fedor and I have been using, as well as listing the steps for what I think would be a slightly improved version.

https://hackmd.io/eWf_RkO6SEuCy5g9-6etMA

Previously, I've done this all with a series of sed/tr/grep/multiple files/etc - obviously not ideal and we need to encode this better for data pipeline use.   Planning to discuss in meeting on 22nd June.
