### ISSUE TITLE
Improve code coverage in testing

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#461]
Particularly should focus on Epidemiology and Climate Pref sections of `src` - but Biodiversity also needs some attention.

**Comment by jwscook** [comment]
This links with https://github.com/ScottishCovidResponse/Simulation.jl/pull/68, which is proof of principle for running something deterministically. In the case of the PR it's a deterministic model run, but it could equally be a deterministic unit test.
