### ISSUE TITLE
Array access out of bounds in getstat

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#465]
There is an invalid array access in output.cc:getstat.  I am running with

./run mode=sim model=irish simtype=smallsim area=1024 seed=0 period=16 transdata=I,H,reg,cases.txt transdata=H,D,all,deaths.txt housedata=house.txt outputdir=Output

i.e. with 1 MPI process, which is all that is needed for simulation.  

This is not visible with GCC on linux (silent error), but with clang on macOS, I get a segfault.  If you compile with array bounds checking (CXXFLAGS = ... -D_GLIBCXX_DEBUG), it reports:

```
/usr/include/c++/7/debug/vector:417:
Error: attempt to subscript container with out-of-bounds index 1, but 
container only holds 1 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7fff5a2b0a60 {
      type = std::__debug::vector<double, std::allocator<double> >;
    }

Program received signal SIGABRT, Aborted.
```
Running with gdb gives more information:
```
#4  0x000056368aaa1de3 in getstat (vec=std::__debug::vector of length 1, capacity 1 = {...}) at output.cc:377
377		stat.CImin = vec[i]*(1-f) + vec[i+1]*f;
``` 
In this case, vec is size 1, so presumably i = 0 and i+1 is out of bounds.

**Comment by ianhinder** [comment]
Would this be a correct fix?
```diff
diff --git a/output.cc b/output.cc
index 0684647..53f506b 100644
--- a/output.cc
+++ b/output.cc
@@ -372,12 +372,20 @@ STAT getstat(vector <double> &vec)
        stat.mean = sum; 
        
        sort(vec.begin(),vec.end());
+       
+       if (n >= 2)
+       {
+               i = int((n-1)*0.05); f = (n-1)*0.05 - i;
+               stat.CImin = vec[i]*(1-f) + vec[i+1]*f;
                        
-       i = int((n-1)*0.05); f = (n-1)*0.05 - i;
-       stat.CImin = vec[i]*(1-f) + vec[i+1]*f;
-                       
-       i = int((n-1)*0.95); f = (n-1)*0.95 - i;
-       stat.CImax = vec[i]*(1-f) + vec[i+1]*f;
+               i = int((n-1)*0.95); f = (n-1)*0.95 - i;
+               stat.CImax = vec[i]*(1-f) + vec[i+1]*f;
+       }
+       else
+       {
+               stat.CImin = vec[0];
+               stat.CImax = vec[0];
+       }
 
        sd = sqrt(sum2 - sum*sum);
        for(i = 0; i < n; i++) vec[i] = (vec[i]-sum)/sd;
```

**Comment by ianhinder** [comment]
@rwj11 , since as you pointed out the results should be the same, due to the multiplication by zero, please could you make a branch and PR with this change so I can merge it in?  thanks!

**Comment by rwj11** [comment]
The change is already in dev, committed by you at ScottishCovidResponse/CoronaPMCMC@e3cad7a4
I don't think I have the data to be able to verify the fix.

**Comment by ianhinder** [comment]
Compiling with GCC and "make DEBUG=1" enables array bounds checking, which would originally have resulted in a runtime error when running 
```
./run inputfile="examples/sim.toml"
```
It now does not give such an error, and by visual inspection, indeed I had already fixed this, so I confirm that problem is gone.
