### ISSUE TITLE
Quick fix to speed up EpiGenerate.jl  - virusupdate!

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#468]
The summation at the after the loop over classes can be pulled into the loop. This helps for two reasons: less allocation; and it gives the threads more to do as well making it faster.

**Comment by jwscook** [comment]
See also https://gist.github.com/jwscook/2a9f080a96a01d62a805a9f0f2b64244

This clearly not a "quick" fix

**Comment by claireh93** [comment]
Closed with ScottishCovidResponse/Simulation.jl#55
