### ISSUE TITLE
Memory allocation in threaded loops

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#470]
Need to investigate where memory allocation is happening in the code, as running the `Scotland_run` model for 1 year on 32 cores still allocates ~500Mb. It's difficult to pin down these allocations using `julia --track-allocation=user`, so perhaps investigation with `julia --track-allocation=all` might be needed. The jump from 1->2 cores doesn't seem to speed things up as much as we would expect.

In particular, we should focus on all of the update loops: `virusupdate!` is slowing things down at the moment. I have also noticed a discrepancy between calling `simulate!` and `simulate_record!` in terms of allocations that might be addressed.

This ideally should be run on the branch ScottishCovidResponse/Simulation.jl#51 which will hopefully be merged in soon - let me know if there are any problems with the branch as it stands.

**Comment by claireh93** [comment]
@wytbella I have tried to write up what we talked about yesterday in issue form, but let me know if there are more details needed

**Comment by wytbella** [comment]
Thanks @claireh93! That makes sense.

I just want to ask whether you just want me to have a "one-off" investigation or you want some tools to be built in permanently?  I was original thinking about using this pkg: https://github.com/KristofferC/TimerOutputs.jl (probably add `@timeit` in front of a few "XXupdate!" functions). Is that what you'd expect?

**Comment by claireh93** [comment]
Hi @wytbella, I was imagining a one-off investigation in the first instance, but if there's anything you think could easily be incorporated to the code base to make this easier to do in the future then that would be cool too!

**Comment by claireh93** [comment]
Can be closed for now - open branch on ScottishCovidResponse/Simulation.jl#59 with code for investigation of memory allocation.
