### ISSUE TITLE
Update README.md for new version of model

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#472]
The README.md file needs to be updated for the changes to the model in [b7f81f83](https://github.com/ScottishCovidResponse/CoronaPMCMC/commit/b7f81f83a2d4e559a5631d5086371ad7127896c2).

**Comment by chrispooley** [comment]
An updated version of the readme has been added. Further documentation on the software use and algorithm is in preparation, but this will take some time...
