### ISSUE TITLE
Change name of executable to coronapmcmc

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#473]
The executable is currently called "run".  Usually, when there is just one executable, it is given a name reflecting the name of the software.  I would keep it all lowercase to make it easier to type. So "coronapmcmc".   @chrispooley, is this OK?

I actually had a convenience script called "run" which I lost because I checked out the new version of the code, ran "make clean", and make deleted my script as it thought it was the executable!

**Comment by chrispooley** [comment]
The executable has been changed from ./run to ./beepmbp
