### ISSUE TITLE
Make Simple network sim stochastic

### ISSUE THREAD

**Issue by FiodorG** [ScottishCovidResponse/SCRCIssueTracking#474]
Currently simple network sim does not assume any randomness: each random quantity is replaced by its expectation. Therefore the model can be run only once, we don't need Monte Carlo tools.

For example, if we have 5000 asymptotic, and the A->I proba is 10%. Right now we do 5000*0.1, but we could throw a coin 5000 times and see how many of the individuals pass into the next stage.

The purpose of this issue is to make the model fully stochastic. This will allow for more correct inference (in the sense of having realistic uncertainty around parameters), as well as modelling super spreaders (e.g. by using heavy tailed distributions on contacts).

**Comment by anthonyohare** [comment]
If we ran the model in a stochastic fashion, in Fiodor's example of 5000 asymptotic, and the A->I probability is 10%, we would 5000*0.1=500 new I individuals as an average over many Monte Carlo simulations but the distribution of new I's would be normally distributed. 

A not-very-quick but dirty 'fix' would be to mimic a Monte Carlo simulation by replacing the A->I probability with a mean and standard deviation (of say 10% and 2% respectively and then calculating the number of new I as 5000*np.random.normal(0.1, 0.02).

A nicer way may be to have a function that decides whether or not to apply this pseudo-MC suggestion or not based on a [global] flag so we can switch between the two modes.

def get_probability(mean, std):
    if RUN_STOCHASTIC:
       return np.random.normal(mean, std)
   return mean
