### ISSUE TITLE
Potential index bug in virusupdate!

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#479]
Is this line correct? 

https://github.com/ScottishCovidResponse/Simulation.jl/blob/cdf065d58bb54eae020fe2fe18ebdc84eb39fd25/src/Epidemiology/EpiGenerate.jl#L76

I'm getting 

```
ERROR: LoadError: TaskFailedException:
BoundsError: attempt to access 1×16 Array{Int64,2} at index [2, 1]
```

And without the line, tests pass.

**Comment by claireh93** [comment]
Hmm, I don't seem to be able to recreate this error on single/multithreads - is this on the latest version of claireh93/movement? The line should be correct, it's storing force of infection in the landscape as well as the environmental reservoir

**Comment by jwscook** [comment]
Yep it's on the latest version of `claireh93/movement`.

**Comment by jwscook** [comment]
My mistake, I needed to `fetch` again.
