### ISSUE TITLE
Log version number and git commit hash

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#498]
Find a way to write the version number and git commit hash in the log for every run.

The version number should come from build.gradle.

It should hopefully be possible to use gradle to get the commit hash, and put it into a file, perhaps generating 'VersionNumber.java'.  I'm not sure how to do this, but this google search might give some pointers:
https://www.google.com/search?client=firefox-b-d&q=gradle+get+current+git+commit+hash

**Comment by BlairArchibald** [comment]
Implemented by https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/128
