### ISSUE TITLE
Many tests create temporary files that are not currently deleted

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#501]
See https://github.com/ScottishCovidResponse/simple_network_sim/pull/67#pullrequestreview-435776377

**Comment by widdowquinn** [comment]
I think this may be able to be handled by `pytest`'s `tmp_path` fixture. I'm happy to take this on.

**Comment by widdowquinn** [comment]
The only test output I could see being left behind after a local `pytest` (macOS) was:

```bash
./tests/test_data/data_pipeline_inputs/output/data.csv
./tests/test_data/data_pipeline_inputs/output/simple_network_sim/outbreak-timeseries/data.csv
```

`outbreak-timeseries/data.csv` gets created/regression-tested in `test_sampleUseOfModel.py::test_run_seeded()` so might be at the root of #441. `output/data.csv` gets tested in `test_data.py::test_write_data()`. The locations are defined in `data_pipeline_inputs/config.yaml` so I *think* can't be handled neatly with the `tmp_path` fixture as I'd hoped.

Instead, I've added a fixture called `teardown_remove_data` that cleans up the `data_pipeline_inputs/output` directory when the `pytest` session closes. There may be a better name for this.

Were there other files being left behind? Two doesn't seem like many, and I may be missing some.

Note: I also updated `spec-file-macos.txt` to bring it up to date with the Linux equivalent.

**Comment by bobturneruk** [comment]
It was the `delete=False` that we needed to get tests to run on Windows e.g. https://github.com/ScottishCovidResponse/simple_network_sim/blob/46ee257294405501b60b3dce8e84bc563fe9bf02/tests/utils.py#L30

I think "many" was probably an overstatement on my part though!

**Comment by bobturneruk** [comment]
Pretty sure having these files:

```bash
./tests/test_data/data_pipeline_inputs/output/data.csv
./tests/test_data/data_pipeline_inputs/output/simple_network_sim/outbreak-timeseries/data.csv
```

Causes `test_run_seeded` to intermittently fail on windows.
