### ISSUE TITLE
Make this a Python package

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#504]
Also drop conda package support unless the effort involved in maintaining it confers some great benefit.

**Comment by bobturneruk** [comment]
Are there benefits to PyPi over using pip to install from github?

**Comment by bobturneruk** [comment]
Conda support is easy to maintain and should be kept.

**Comment by aflag** [comment]
The benefit of installing from PyPI is that you don't need to recompile the package each time. So it's more reproducible in that sense. But given we don't have any C libraries, that's probably not really a concern.
