### ISSUE TITLE
Write a converter

### ISSUE THREAD

**Issue by magicicada** [ScottishCovidResponse/SCRCIssueTracking#507]

**Comment by magicicada** [comment]
That NRS link should actually be: https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/population/population-estimates/2011-based-special-area-population-estimates/small-area-population-estimates/mid-2016/detailed-data-zone-tables

**Comment by anthonyohare** [comment]
sorry @magicicada if you've been working on this, once I finished the school age data this looked similar. So similar in fact there is a bit of overlap in the scripts that it makes sense to combine the scripts to process the data from NRS.

I'm attaching what I've done (as a .txt file) but I should be able to finish by Monday afternoon.

[getPopulationEstimates.py.txt](https://github.com/ScottishCovidResponse/SCRCIssueTracking/files/4873634/getPopulationEstimates.py.txt)
