### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#53]

**Comment by johnnonweiler** [comment]
I'm expecting we'll probably use GitHub Actions, as suggested by Ian Hinder in a Zulip chat.  Also in Zulip, William Pettersson suggested he might be able to take on issues like this one.

**Comment by vinopm** [comment]
de4ee34d08037788ee95b4ede0d79dfcd982bca8

**Comment by vinopm** [comment]
https://github.com/ScottishCovidResponse/Contact-Tracing-Model/pull/2

**Comment by vinopm** [comment]
https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/5

**Comment by johnnonweiler** [comment]
This is mostly done, but for some reason the Action is not running on the Covid_Simulation_Model repository.  I suspect that this has something to do with the repository being forked, but have not been able (yet) to find a way to enable it.  It may be that admin rights are required on the repository to sort this out, so I'll take it from here.  Thanks again @vinopm !

**Comment by johnnonweiler** [comment]
@vinopm Seems to have figured out the problem, so assigning this back to him!

**Comment by vinopm** [comment]
https://github.com/ScottishCovidResponse/Contact-Tracing-Model/pull/4

**Comment by vinopm** [comment]
Added 2 PR's above to integrate CI status badges into the readme pages
