### ISSUE TITLE
Create an end-to-end data pipeline flow for simple network sim

### ISSUE THREAD

**Issue by mrow84** [ScottishCovidResponse/SCRCIssueTracking#534]
A series of scripts to do the following:

1. Ingest and upload inputs
2. Download inputs
3. Run model
4. Upload outputs

**Comment by mrow84** [comment]
My plan is to create a directory called `data_pipeline_flow` to house what I'm doing, the aim being that from within that directory you can run an end-to-end flow of simple network sim's interaction with the data pipeline, assuming that we have all of our own inputs. This is not intended to be permanent, but is the next stage of working out what integrating a model into the data pipeline will entail.

**Comment by magicicada** [comment]
I've found some of the data munging to be frustratingly manual - e.g. there exists nowhere that I can find online a complete-ish listing of population estimates at the geography that Google uses, so I've manually aligned their regions to the regions that we do have data for, and stored this in a file.  The data on those population breakdowns come in a CSV file from the census with many other tables within the same CSV file, separated by text and blank lines, so I've manually copied out the table we need into another file.  Not sure how surmountable some of these things are?  Relatedly, was thinking of uploading these files and associated description of manual process and scripts for the mobility modified - should that wait until progress on this is made, or go somewhere else?

**Comment by bobturneruk** [comment]
Sounds dreadful! I think we should make time to discuss this on Monday (2020076), and more time at a later point, if needed. I think we should be able to figure something out between us. I feel like documentation is fine if automation can't be achieved. @mrow84's [`data_pipeline_flow`](https://github.com/ScottishCovidResponse/simple_network_sim/tree/upload_testing/data_pipeline_flow) is worth a look as it lays out how one might like to do a run. Where the data munging fits into this, we must figure out.

I guess if data is fairly static we could "publish" the munged version somewhere (along with the munging instructions) and work from that as an input to the "pipeline"?

**Comment by magicicada** [comment]
Yes - at least so far the manually munged bit is static - the potentially dynamic bit is downloadable and parseable conveniently.

**Comment by mrow84** [comment]
The ingesting and uploading of inputs is now out of scope.

**Comment by bobturneruk** [comment]
This has been subsumed by https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/664
