### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#54]

**Comment by johnnonweiler** [comment]
For an example of Sam's preferred style, see the SEIR-Model project.

**Comment by sam-brett** [comment]
This ticket is the parent of #125 #126 #127 #128 #129

**Comment by vinopm** [comment]
@sam-brett let me know if I can help with this one

**Comment by sam-brett** [comment]
@vinopm Hi Vino, 

I've pushed a new branch that has some unit tests on it. There are a few tests across a couple of packages, but the utilities, io and contact packages don't have any tests yet. If you don't mind taking a stab at the io, utils and contact packages, I can finish off the people package. Once we hit 80% I'm going to call that a release. In the meantime I'll probably branch from this branch for some of the changes we'll be making for the next release. Feel free to get in touch if you need anything. I've added Mockito and PowerMock to the dependencies so hopefully that should make testing easier. 

Cheers
Sam

**Comment by vinopm** [comment]
Perfect, will work on getting that done. Thanks @sam-brett

**Comment by vinopm** [comment]
https://github.com/ScottishCovidResponse/Contact-Tracing-Model/pull/7

**Comment by sam-brett** [comment]
complete
