### ISSUE TITLE
DataPipeline: add get_write_group() and get_read_group()in StandardAPI 

### ISSUE THREAD

**Issue by qingfengxia** [ScottishCovidResponse/SCRCIssueTracking#542]
Currently pipeline python API, write_array(Array) ,where Array is an alias to numpy.array. It does not holds metadata like dimension_i_units. so I need get access to “H5Group” python object from C++. I used object_file(file_format.py) 's "get_write_group()" as no such method in StandardAPI. I run into some error, I am not sure if object_file(file_format.py) 's "get_write_group()" are designed to be used by users.

I wonder if you can provide get_write_group() and get_read_group()in StandardAPI ?

Thank you.

there is some discussion in zulip  channel  `python API`

**Comment by mrow84** [comment]
This is no longer necessary.
