### ISSUE TITLE
Review unit tests

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#55]
There are now multiple issues about adding unit tests, so I am renaming this from "add unit tests" to "Review unit tests", with a view to reviewing what's left to do after the other tests have been added.

Ideas of some things to include in checks (from Paul):

- Population size. Live + dead people should remain constant. However people are not necessarily constantly in their house, so this unit test needs to check all places where people can be.
- Epidemic doubling time. The time that it takes for the number of cases to double should be limited. Needs more thought, but at the very least we can put a range around this – so if the epidemic today is twice the size of yesterday then something has gone wrong. But this thing that has gone wrong could be the parameters rather than the code.
- Some people should be dying, but not everybody, it should be around 3% of infected people
- People should be using businesses – all households should periodically visit shops and restaurants
- All children should go to school
- 50% of infants should go to nursery
- During lockdown usage of non-key premises should stop
- During lockdown people should stop visiting neighbours

**Comment by johnnonweiler** [comment]
This issue was written a long time ago.  @bobtaylor12 - Please could you comment on what remains to be done here?

**Comment by bobtaylor12** [comment]
This is an ongoing task really. As new code is written I have been reviewing what new tests might be required. Strictly speaking the author of the code should write all tests but in the interests of speedy development this is not always happening.

**Comment by johnnonweiler** [comment]
Thanks @bobtaylor12 .  I appreciate you keeping on top of this!

I think if this is an ongoing thing, then there's not much point in keeping this general issue open, so let's new add issues when we spot a particular place where additional tests are required.
