### ISSUE TITLE
Update transitions between compartments. 

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#56]
Currently the model assumes fixed time periods for incubation and infection, but we should ideally be using available information on distributions for these periods.

**Comment by sam-brett** [comment]
Both AlertStatus and VirusStatus have a transitionTo method which checks the next stage is a valid transition. ie someone can't go from dead -> infected

**Comment by sam-brett** [comment]
Will be closed after Pr11
