### ISSUE TITLE
Fix segfault when parameter value is blank

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#563]
Running with "nchain=" caused a segfault for me, a while back.  Check whether this is still the case, and fix the code. The string manipulation code can probably be replaced with standard functions.

**Comment by rwj11** [comment]
I don't get a segfault, but do see an ugly-looking abort due to an uncaught exception escaping.

**Comment by ianhinder** [comment]
Can you add a nicer exception handler?

**Comment by rwj11** [comment]
I'll add a minimal handler just to make things look less nasty if this specific error occurs.  There should probably be a feature ticket (and associated discussion) about general policy for error handling?

**Comment by ianhinder** [comment]
Yes - would you mind creating such a ticket and making a suggestion? Thanks!

**Comment by ianhinder** [comment]
Addressed in https://github.com/ScottishCovidResponse/CoronaPMCMC/pull/4.
