### ISSUE TITLE
Additional statistics

### ISSUE THREAD

**Issue by vinopm** [ScottishCovidResponse/SCRCIssueTracking#564]
Additional statistics that Louise mentioned she would like in the model:

- Total person days in isolation
- Total number of people infected
- Total number of people who are contacted for tracing (i.e. when alert status changes from NONE to ALERTED)

- Calculation of R<sub>0</sub>: for a given timestep, the value of R will consider all future infections from that timestep.
- Calculation of R with weekly rolling average (optional as Sibylle has agreed she can produce this in R - this will help keep our code base simple if we are not required to implement it)

**Comment by sam-brett** [comment]
PR 37
