### ISSUE TITLE
New Compliance parameter

### ISSUE THREAD

**Issue by vinopm** [ScottishCovidResponse/SCRCIssueTracking#565]
- We need a new compliance parameter to represent individuals who are likely to not report their symptoms (i.e. if they are only mildly symptomatic and do not want to be told to isolate).

- Have this as a single parameter for now, but in the future we may want to represent this as a function of age.

- The existing compliance parameter should probably be renamed to something like 'isolationCompliance' which represents the likeliness of the individual adhering to isolation advice.

**Comment by sam-brett** [comment]
PR 37
