### ISSUE TITLE
Parameterizing for output folder

### ISSUE THREAD

**Issue by vinopm** [ScottishCovidResponse/SCRCIssueTracking#568]
Currently we have a way to override the input folder, we need to implement something similar for the outputs produced by the model.

gradlew run --args='--overrideInputFolderLocation=input/scenarios/scenario0' is used to override the input folder. 

The purpose of this is to be able to allow @sibylleM  and @maxlogutility  to run many simulations in parallel, and have the inputs and outputs independently specified for each of the runs.

This is a blocker for @sibylleM and @maxlogutility to carry out their simulation runs

**Comment by sam-brett** [comment]
Complete
