### ISSUE TITLE
Add additional stratification

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#57]
e.g. age classes

**Comment by johnnonweiler** [comment]
Age classes now exist, but are not yet being used for anything.

**Comment by sam-brett** [comment]
![Screenshot 2020-05-19 at 16 46 39](https://user-images.githubusercontent.com/64466838/82348123-5b3ac380-99f0-11ea-8c8c-fb934bf3ce39.png)

Current status. Following closure of PR11, this will be closed.
