### ISSUE TITLE
More epidemiological compartments

### ISSUE THREAD

**Issue by johnnonweiler** [ScottishCovidResponse/SCRCIssueTracking#59]
The plan is to initially use a simple SEIR model, but we likely need Susceptible, Incubating (possibly multiple incubating stages), Symptomatic Infecteds, Asymptomtic Infecteds, Hospitalised (with possible breaks downs into critical and non-critical care). Not all of these will be critical to the contact tracing but may be needed in order to validate the model against case and deaths data.

**Comment by sam-brett** [comment]
This should be partially completed by PR11. Further additions may be made when @LouiseMatthews receives data from Ireland.
