### ISSUE TITLE
Crash when running sim.toml

### ISSUE THREAD

**Issue by rwj11** [ScottishCovidResponse/SCRCIssueTracking#590]
$ ./run inputfile=examples/sim.toml
    ...
    free(): double free detected in tcache 2
    ...
    Aborted (core dumped)
on Linux/gcc/openmpi.

**Comment by ianhinder** [comment]
@rwj11 has made a pull request here: https://github.com/ScottishCovidResponse/CoronaPMCMC/pull/5.

**Comment by ianhinder** [comment]
Closed by https://github.com/ScottishCovidResponse/CoronaPMCMC/pull/5.
