### ISSUE TITLE
Add example simulated data to examples/Data_example

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#608]
At the moment, there is example data for populations, flow, mixing, etc in examples/Data_example. This is enough to run a simulation, which then generates the data for the transitions (cases, deaths, etc), which is then enough to run inference.  

However, it's not possible to run inference directly on the provided data, as the transition data isn't provided.  I think it would make sense to add simulated data to examples/Data_example, so we can run inference directly from it without having to run a simulation first.  This will help a lot with regression testing. With the recent change to write simulated data into outputdir rather than datadir, this shouldn't cause any problems with git.  @chrispooley , what do you think?  Can I commit the simulation results to this directory?

**Comment by chrispooley** [comment]
This has now been added.
