### ISSUE TITLE
Allow setting random seed via standard API

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#611]
Some of the API functions are defined to return random results. We need a way to deterministically set the random seed via the standard API. In Python, this can be a straightforward wrapper around np.random.seed(0), as is done in test_standard_api.py. This should be a part of the official spec, so that all implementations use it.

**Comment by mrow84** [comment]
This should be invalidated by #640.

**Comment by ianhinder** [comment]
Yes it is, thanks. This issue can be closed once it's implemented (just don't want it to get forgotten in case it is decided to reverse the decision to implement #640).
