### ISSUE TITLE
Removing timing data from MCMCdiagnostic.txt

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#612]
Can I remove the writing of the timer to MCMCdiagnostic.txt? It makes the file non-reproducible, which makes regression-testing difficult.

**Comment by ianhinder** [comment]
In the chrispooley branch, more timing information has been added to this file.  Timing information is very useful, so I think it should be kept, but can it be moved to a separate file? That file can then be excluded from regression test comparisons (and maybe used for performance regression tests!).

**Comment by ianhinder** [comment]
I've got a version of this locally - it writes the timing information to MCMCdiagnostic_timings.txt. OK to commit it?

**Comment by chrispooley** [comment]
Hi,

I've just removed then from the diagstics file, but if you have put them into a different file that is fine too. Really they are useful only to me, and they won't we in the final version of the code.

**Comment by ianhinder** [comment]
Thanks
