### ISSUE TITLE
Hang during MBP

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#616]
The code could hang during the MBP function. This failure was not reproducible, as the code in question depends on timings, which can change each time it is run. This makes it very difficult to debug.

Summary of email discussion:

rwj11:

> FWIW, I was finding on my machine when inf.toml was run serial, control flow could reach this line in MBP.cc
>  timeloop = 10*double(timeproptotsum)/(ntimeproptotsum*CLOCKS_PER_SEC);
with ntimeproptotsum == 0, which slows things up pretty much indefinitely...

chrispooley:
> Thanks for that. I see, so we get a problem if the computer says that a proposal takes no time (due to finite accuracy of CPU clock). I've just corrected this so it should still work.

rwj11:

> What actually happens for me in inf.toml run serial is that here:
> ```
> if(model.param[th].min != model.param[th].max){ mbpchain[p]->proposal(th,samp,burnin); ntimeprop++;}
> ```
> the test never passes, so ntimeprop never incremented.

> In more detail: for the first sampling, the code only loops once and selects th==8, for which the min and max are equal (both 10).  So it doesn't call proposal(), or increment ntimeprop, which results in timeloop being set to "Inf".  The next time it hits the do{}while loop, it never gets out.

> Ian suggested that I passed on my fix, which was to use defensive programming, and change a line in MBP.cc to
> ```
>  if (ntimeproptotsum>0) timeloop = 10*double(timeproptotsum)/(ntimeproptotsum*CLOCKS_PER_SEC);
> ```

**Comment by ianhinder** [comment]
I've been a bit confused by this issue, which is why I'm writing it up here, so there is a full record.

Chris, above, identified the problem as being due to the clock resolution being too coarse to capture the amount of time taken by proposals, which would result in `timeproptotsum == 0`, and hence `timeloop == 0`.  The do loop would then run only once, as `while(double(clock()-time)/CLOCKS_PER_SEC < timeloop)` would always be false.  This would run one proposal.  If every proposal run in this way took less than the clock granularity, then this would result in a hang. Chris applied a fix in https://github.com/ScottishCovidResponse/BEEPmbp/commit/1a80084de28880bea7ed36bfcae2509fbae1071e. This fix sets timeloop to 1 if `timeproptotsum == 0`.  

Robin, above, identified the actual hang he was seeing as being caused by `model.param[th].min == model.param[th].max`, meaning that ntimeprop == 0, hence ntimeproptotsum == 0 since he was running in serial, and timeloop being set to inf, causing the do-while loop to run forever. His fix was to only change timeloop only if ntimeproptotsum > 0, indicating that timeloop would never be set to inf. 

These are two different possible failure modes of the code.  On balance, I think the best fix includes both of these:
```
// Update the time to run only if some proposals have run, and they took a measurable amount of time
if (ntimeproptotsum > 0 && timeproptotsum > 0) {
	timeloop = 10*double(timeproptotsum)/(ntimeproptotsum*CLOCKS_PER_SEC);
}
```
This catches both failure modes, as far as I can tell.  Chris' version set timeloop to 1 rather than skipping changing it.  timeloop is initially 0.1, so I think it's cleaner just to not change it in this situation.  I have implemented this combined change while merging into dev and the following commit (1b44546 and aa1c536).

**Comment by ianhinder** [comment]
Chris, let me know if this is ok and if so please close this issue.

**Comment by ChrisJefferson** [comment]
Did you mean to assign this to me, or maybe @chrispooley ?

**Comment by chrispooley** [comment]
Yes, this looks fine to me.

**Comment by ianhinder** [comment]
@ChrisJefferson sorry!
