### ISSUE TITLE
Lots of TOML warnings with GCC 4.8.5

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#619]
Chris is seeing lots of compiler warnings from TOML with GCC 4.8.5.

eg

toml11/toml/string.hpp: In instantiation of ‘static void toml::basic_value<C, T, A>::assigner(T&, U&&) [with T = toml::string; U = const toml::string&; Comment = toml::discard_comments; Table = std::unordered_map; Array = std::vector]’:
toml11/toml/value.hpp:216:89:   required from ‘toml::basic_value<C, T, A>::basic_value(const toml::basic_value<C, T, A>&) [with Comment = toml::discard_comments; Table = std::unordered_map; Array = std::vector]’
toml11/toml/literal.hpp:58:32:   required from here
toml11/toml/string.hpp:27:5: warning: unused parameter ‘s’ [-Wunused-parameter]
     string(const string& s) = default;
     ^
In file included from toml11/toml/parser.hpp:10:0,
                 from toml11/toml.hpp:36,
                 from model.hh:10,
                 from output.cc:14:
toml11/toml/value.hpp:173:73: note: synthesized method ‘toml::string::string(const toml::string&)’ first required here
         const auto tmp = ::new(std::addressof(dst)) T(std::forward<U>(v));

I don’t see these with GCC 7.5.0.  It would be good to eliminate them if possible.

**Comment by rwj11** [comment]
I also haven't been able to reproduce this on godbolt for 4.8.5 (or any other version which understands defaulted constructors at all): https://godbolt.org/z/85G68c

**Comment by chrispooley** [comment]
I see. It is a mystery. What would you recommend I do? Can I temporarily disable the -Wunused-parameter warnings? (if that is possible?)... otherwise writing code is rather difficult...

**Comment by chrispooley** [comment]
I should mention I didn't get warnings before from TOML. It is just something that started yesterday when I pulled files... Did the makefile get changed?

**Comment by rwj11** [comment]
Sometimes I've found it useful to have the Makefile load a local configuration file to deal with e.g. incompatible library versions on different systems.  It might be possible to implement something similar, but it's probably worth investigating root causes first.  Switching warnings off tends to mean commits will need tidying after the fact, where it's better to get things right first time.

**Comment by rwj11** [comment]
Yes, more code warnings have been enabled in the Makefile.

**Comment by ianhinder** [comment]
Yes, loading a local configuration file is something I planned to add in the future. Chris: this would mean you could create a file with any local customisations which would be loaded by the main Makefile. For now, I think it's not necessary.

I don't understand why Chris gets these warnings, when that version of the compiler doesn't give the warnings on https://godbolt.org.  I'm worried that somehow Chris is compiling the code in a different way, or something is not being synced correctly when he copies the files to his work machine. I've looked on the BIOSS website, but they don't provide any information about their HPC system.

**Comment by ianhinder** [comment]
@chrispooley Can you tell us what the command
```
cat /etc/redhat-release
```
says on this system? I suspect it is CentOS 7-7 or similar.

**Comment by ianhinder** [comment]
I can reproduce the compiler warnings in a Centos 7.7 docker container, so there's nothing fishy about Chris' setup. Chris, can you type "module avail" on the Linux machine you're getting the warnings on, and send the output to us by email?  They might not be using the module system, but if they are, then a newer compiler might be available.

I don't know why these warnings about unused variables only occur with this old compiler - maybe there are some parts of the code which behave differently depending on whether certain C++11 features are present.

**Comment by rwj11** [comment]
If supporting 4.8.5 on CentOS is required, then can/should that be added to the CI?

**Comment by ianhinder** [comment]
Chris sent us the output of module avail, and it's just the system-provided mpich modules, so there are no other compilers provided by modules. 

@rwj11  Potentially, but at this point it's not really an issue of whether we are trying to support it; it's a question of how to get Chris able to compile without a load of warnings.  

I am going to modify the Makefile on the dev branch to work around these warnings on that compiler.

**Comment by ianhinder** [comment]
I have now pushed a change to the dev branch which eliminates the problematic warnings for the relevant source files: analysis.cc and model.cc.
