### ISSUE TITLE
Delete NDCode and BTV-model

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#62]
Delete the two forks - NDCode and BTV-model - from SCRC organisation to reduce confusion. @paulbessell, is it okay to delete them?

**Comment by paulbessell** [comment]
Help yourself

**Comment by alysbrett** [comment]
Just alerting @johnnonweiler so he is aware

**Comment by alysbrett** [comment]
Done
