### ISSUE TITLE
Ensure there are no hard-coded parameters in the source code

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#629]
We need to make sure there are no hard-coded epi parameters or data in the source code.  @chrispooley can you confirm that this is now the case? consts.hh is where they all were, and they seem to have all been moved to the input files, which is good.

**Comment by ianhinder** [comment]
@chrispooley Can you confirm that there is nothing in the source code that could be considered a hard-code epi parameter or assumption? Everything is now in the input files?

**Comment by chrispooley** [comment]
There are no hard-coded parameters in the code.
