### ISSUE TITLE
Populate mailing list database from personnel data

### ISSUE THREAD

**Issue by richardreeve** [ScottishCovidResponse/SCRCIssueTracking#63]
We need to automatically populate the mailing lists for the different projects from the [personnel](https://github.com/ScottishCovidResponse/personnel) repository toml files.
- names and email addresses are in [people.toml](https://github.com/ScottishCovidResponse/personnel/blob/master/people.toml)
- projects are the toml files in the [projects](https://github.com/ScottishCovidResponse/personnel/tree/master/projects) subdirectory
- the two are linked by github username

**Comment by alysbrett** [comment]
This is a duplicate of #25 where there is some progress...
