### ISSUE TITLE
Identify/Upload sources of model data on data repository

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#656]
For each data item identified in #437 as being sourced from the SCRC data pipeline, we need the following information:

* The identifier/path of the corresponding data structure within the pipeline
* The type (estimate, table, array, etc.) required for the API call to fetch the data
* Whether or not any transformation is required after the data is fetched from the pipeline (e.g. if the data is part of a larger data structure, it may need to be extracted)

**Comment by kzscisoft** [comment]
# Sourcing

## Data sets
| Identifier  | Description | SCRC Remote Address | Comment |
| ------------- | ------------- | ------------- | ------------- |
| `cfr_byage` | Case Fatality Ratio by age group | | |
| `scot_age` | Proportion of population in each age group, by health board<br> (Includes HCW implicitly) | | |
|`scot_data`| Timeseries of observed disease cases, by health board<br>Also stores population of health board | | |
| `scot_data`| Timeseries of observed disease deaths, by health board<br>Also stores population of health board| | |
|`waifw_home`| Age mixing matrix (home only) | | |
|`waifw_norm`| Age mixing matrix (All contact included) | | |
|`waifw_sdist`| Age mixing matrix (excludes school and work contact - social distancing) | | |

## Parameters.ini: [Priors settings]

| Prior identifier  | Description | SCRC Remote Address | Comment |
| ------------- | ------------- | ------------- | ------------- | 
| `pinf` | Probability of infection (non-HCW) | `DataRepository/SCRC/human/infection/SARS-CoV-2/symptom-probability/0.1.0.toml`  | Value is a `point-estimate` as opposed to required Beta `distribution`. No distinction between HCW/non-HCW.|
| `phcw` | Probability of infection (HCW) | `DataRepository/SCRC/human/infection/SARS-CoV-2/symptom-probability/0.1.0.toml`  | Value is a `point-estimate` as opposed to required Beta `distribution`. No distinction between HCW/non-HCW.|
| `chcw` | Mean number of HCW-patient contacts per day  | | |
| `d` | Proportion of population observing social distancing  | | |
| `q` | Proportion of contacts made by self-isolaters | | |
| `ps` | Age-dependent probability of developing symptoms | | |
| `rrd` | Risk of death if not hospitalised | | |
| `lambda` | Background transmission rate  | | |

## Parameters.ini: [Fixed parameters]

| Parameter identifier  | Description | SCRC Remote Address | Comment |
| ------------- | ------------- | ------------- | ------------- | 
|`totN_hcw` | Total population of HCW |  |  |
| `day_shut` | Point in observations where lockdown starts | | |
| `T_lat` | Mean latent period | `DataRepository/SCRC/human/infection/SARS-CoV-2/latent-period/0.1.0.toml ` | Value is `123.12` in remote data vs our `4` suggesting different units?|
| `juvp_s` | Probability of juvenile developing symptoms | | |
| `T_inf` | Mean asymptomatic period | `DataRepository/master/SCRC/human/infection/SARS-CoV-2/asymptomatic-period/0.1.0.toml` | Value is `192` in remote data vs our `1.5` suggesting different units? |
| `T_rec` | Mean time to recovery if infection is symptomatic | | |
| `T_sym` | Mean symptomatic period prior to hospitalisation | | |
| `T_hos` | Mean hospitalisation duration || | |
| `K` | Bed capacity for Covid19 patients | | |
| `inf_asym` | reduction factor of infectiousness for asymptomatic infectious individuals | | |

**Comment by kzscisoft** [comment]
**UPDATE:** Due to there currently being very little overlap between what is available on the registry and what we require, this issue now consists of the following:

- [X] Upload "version 1" of parameters as they currently stand into the new accepted TOML form using the `SCRCdataAPI` templates. This consists of pushing an update to the registry as well as adding the parameters to the `DataRepository` GitHub.
- [x] Upload data itself as "version 1" in the form of HDF5 files to the relevant storage space, add again add entries to the data registry. Ultimately the exact structure of this data is likely to change from the current time series form, but such updates will just form a new version.

**Comment by peter-t-fox** [comment]
Situation has ben clarified: data are now available on the repository.
