### ISSUE TITLE
Remove RCall dependency

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#66]
Only one test relies on RCall for entire package - we can remove this for now.

**Comment by claireh93** [comment]
@jwscook @AlexRobson RCall has now been removed from the package to streamline things - perhaps the travis stuff could be amended on this same branch?

**Comment by jwscook** [comment]
@claireh93 I'll do that.

**Comment by jwscook** [comment]
PR when ready - travis "should" work

**Comment by claireh93** [comment]
Done with ScottishCovidResponse/Simulation.jl#12
