### ISSUE TITLE
Update to use v0.7 of data_pipeline_api

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#660]

**Comment by mrow84** [comment]
The newest version of the API contains a breaking change. We have to update [all uses of the StandardAPI constructor](https://github.com/ScottishCovidResponse/simple_network_sim/search?q=StandardAPI&unscoped_q=StandardAPI) to use [`StandardAPI.from_config`](https://github.com/ScottishCovidResponse/data_pipeline_api/blob/master/data_pipeline_api/standard_api.py#L43).
