### ISSUE TITLE
End-to-end run of simple network sim through data pipeline

### ISSUE THREAD

**Issue by mrow84** [ScottishCovidResponse/SCRCIssueTracking#664]

**Comment by bobturneruk** [comment]
Plan:

- [x] Upload [current test data](https://github.com/ScottishCovidResponse/simple_network_sim/tree/master/sample_input_files) into "simple_network_sim_test" namespace
- [x] Make an appropriate `config.yaml`
- [x] Download data
- [x] Run the model
- [x] Upload the output

**Comment by bobturneruk** [comment]
I've now completed this. What I did is recorded here: https://github.com/ScottishCovidResponse/simple_network_sim/pull/115
