### ISSUE TITLE
Inclusion of Additional Distributions for the EERA Model

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#693]
The EERA Model requires a few extra distributions not yet included within the `data_pipeline_api`, the exact use of these distributions can be found within the TOML files created by @peter-t-fox [here](https://github.com/ScottishCovidResponse/temporary_data/tree/peter-t-fox/444-add-eera-params-for-staging/temporary/Covid19_EERAModel/prior-distributions) with address `<distribution_name>/data/1.toml`. I am aware these TOML files are now dated in their form but I am working on using the available upload templates to create new ones. 

These distributions are:
- Uniform
- Beta
- Poisson

I am adding the EERA Model label to this issue just so we can keep track of it too, if any more information is needed about these distributions do let me know below. Thanks!

**Comment by mrow84** [comment]
Now being addressed in #671.

**Comment by kzscisoft** [comment]
Apologies @mrow84 having been away from the model for a while I failed to notice that our distribution list increased in size since the TOML files Peter created. Having looked through:
https://github.com/ScottishCovidResponse/Covid19_EERAModel/blob/dev/src/Random.h
We also require:

* Multinomial

* Binomial

@peter-t-fox can you confirm that this is the only location where distributions are initialised please?
