### ISSUE TITLE
Benchmarking serial performance.

### ISSUE THREAD

**Issue by jwscook** [ScottishCovidResponse/SCRCIssueTracking#7]
Benchmark, identifiy bottlenecks and potentially fix them.

Target performance of outcome of #12

**Comment by wytbella** [comment]
Can I request some clarifications on this issue?

- It's my first time writing a pkg benchmark. I plan to use [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl) and follow some examples [like this one](https://github.com/tkf/Transducers.jl/tree/master/benchmark). Is that ok? Do you have other suggestions?

- Could you list down some functions you want to have benchmark on in terms of priority (I suppose `simulate(_record)!`? any other functions?)? I saw a "Benchmarking.jl" file in "examples". Any suggestion as how I should refer to it? Still not very familiar with all the source functions, so would greatly appreciate more explanations.

**Comment by jwscook** [comment]
It would be good to point PkgBenchmark at the files in examples/Epidemiology on `dev`. I should mention that the title and description were too terse; we should be benchmarking, identifying bottlenecks and either fixing performance bugs or identifying changes to architecture to enable speed up.

@wytbella can you keep an eye on #12 too? The outcome of that will be the one we want to go fastest. 

@claireh93 is there anything else specifically that you think should be benchmarked?

**Comment by wytbella** [comment]
> It would be good to point PkgBenchmark at the files in examples/Epidemiology on dev

Benchmark all the files in [examples/Epidemiology](https://github.com/ScottishCovidResponse/Simulation.jl/tree/dev/examples/Epidemiology). Should I build my branch from `dev` or just merge to `dev`? 

> we should be benchmarking, identifying bottlenecks and either fixing performance bugs or identifying changes to architecture to enable speed up.

The example files call `simulate_record!`. I suppose there is something inside that function you want to benchmark as well to spot out the bottleneck?

> can you keep an eye on #12 too? The outcome of that will be the one we want to go fastest.

Do you mean to add benchmark to cover those canonical scripts (or each component inside them)?

**Comment by jwscook** [comment]
Just cover the whole script at the moment. This work should show which functions warrant further investigation.
