### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by ianhinder** [ScottishCovidResponse/SCRCIssueTracking#703]
We have some compiler warnings again. See https://github.com/ScottishCovidResponse/BEEPmbp/actions/runs/183411879. These should be fixed.

**Comment by rwj11** [comment]
Closed at https://github.com/ScottishCovidResponse/BEEPmbp/pull/19
One clang-analyzer warning remains on llvm 6.0, which does not appear using llvm 10.0.

**Comment by ianhinder** [comment]
I've update CI to use clang-tools-10, and the warning indeed goes away. See https://github.com/ScottishCovidResponse/BEEPmbp/actions/runs/189132525.

**Comment by rwj11** [comment]
Great, thanks.
