### ISSUE TITLE
Different Infection Rates

### ISSUE THREAD

**Issue by sam-brett** [ScottishCovidResponse/SCRCIssueTracking#717]
different probabilities of transmission for asymptomatics, pre-symptomatics, symptomatic and severe [apologies that this didn’t come up sooner in conversation]

**Comment by sibylleM** [comment]
Just to add: right now everyone is treated the same, there is no infectiousness criteria in that sense, so we should change this (e.g. asymptomatic only half as infectious as the symptomatics, etc).

**Comment by sam-brett** [comment]
complete awaiting review
