### ISSUE TITLE
Automatic code formatting causes merge conflicts on master branch

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#744]
The CI is configured to automatically run a code-formatting tool `clang-format` whenever a merge occurs to the master branch. 

The format specifies an `IndentWidth` of 2 spaces, which means that almost all of the code gets updated away from its standard indentation of 4 spaces when the merge from `dev` to `master occurs.

Since no merge back from `master` to `dev` occurs with the automatics changes, subsequent attempts to merge to `master` will fail because of merge conflicts (triggered by any subsequent changes made on `dev`). This renders the master branch effectively unusable for doing releases.

- [ ] Need to either fix the `clang-format` configuration, or disable it entirely
- [ ] May need to delete the master branch and re-create it and the existing releases.

**Comment by kzscisoft** [comment]
This might be of use later https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configuring-style-with-clang-format

**Comment by rwj11** [comment]
It may also be worth investigating e.g. `git merge -Xignore-space-change`

**Comment by peter-t-fox** [comment]
Thanks to every one for the feedback. For the moment, my fix will be:

* Revert the commit on the master branch which applied the code formatting. (This will mean that there won't be any effect on the previous release)
* Make a new commit on master removing the automatic formatting from the workflow.

Then we should be able to merge from `dev` as normal, since the changes that triggered the conflicts will have been reverted.
