### ISSUE TITLE
Alter inference ends file to match structure of prediction full file

### ISSUE THREAD

**Issue by peter-t-fox** [ScottishCovidResponse/SCRCIssueTracking#749]
The prediction `full` file now has the following format, where the epidemiological compartments are all located on a single row.

```
iter, day, age_group, S, E, E_t, I_p, I_t, I1, I2, I3, I4, I_s1, I_s2, I_s3, I_s4, H, R, D
0, 0, 0, 1266783, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
...
```

The `full` file produced in inference mode is formatted as:

```
iterID,age_group,comparts,value
2, 0, 0, 780556
2, 0, 1, 111340
2, 0, 2, 0
2, 0, 3, 39191
2, 0, 4, 0
2, 0, 5, 56667
2, 0, 6, 48062
2, 0, 7, 39969
...
```
where each compartment gets a row to itself. 

Inference I/O code should be updated to match the prediction mode format.

**Comment by kzscisoft** [comment]
- [X]  Change headers to match as above
- [x] Produce all output files in an identical manner using similar `WriteInferenceXHeader` functions etc
