### ISSUE TITLE
Impact of Travis T&C changes

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#757]
Travis T&Cs have changed - what is the impact of repos. using Travis? Probably need to change from travis-ci.org to travis-ci.com at least.

**Comment by olexandr-konovalov** [comment]
GAP is migrating to GitHub actions - we might follow the same path.

**Comment by bobturneruk** [comment]
Projects can migrate via https://travis-ci.com/organizations/ScottishCovidResponse/migrate GitHub actions is probably a better long term plan, but I have now migrated simple network sim.
