### ISSUE TITLE
Investigate splitting C++ API into its own repository

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#768]

**Comment by kzscisoft** [comment]
I can confirm that the C++ implementation works fine within its own repository. I have set CMake to fetch and install any external dependencies needed including the `data_pipeline_api` python module so only:

```bash
cmake . -Bbuild
cmake --build build
```
needs to be run.

**Comment by kzscisoft** [comment]
@bobturneruk sounds like this issue is now irrelevant, as discussed we are moving more towards an independent C++ API now. I can conclude that the answer is "yes" it can run from a separate repository.
