### ISSUE TITLE
Feasibility study for possible C++ standalone implementation

### ISSUE THREAD

**Issue by kzscisoft** [ScottishCovidResponse/SCRCIssueTracking#774]
Determine whether moving to a standalone C++ API is feasible time wise and based on availability of easy to use HTTP connection libraries. Related to #768.

**Comment by kzscisoft** [comment]
Updates are here: https://github.com/kzscisoft/SCRC-Cpp-API

**Comment by kzscisoft** [comment]
Just to restate what I said during the meeting:

The core aspect of connecting to the API and sending requests and parsing returned JSON is possible using the chosen JSONCPP and libcurl libraries. Issues arise when trying to mirror the same object structure as the Python as libraries do not exist so readily for C++ as modules do for Python. You find yourself going sideways more than forwards with having to mirror methods in the imported Python modules themselves as well as the API.

I shall therefore start considering a unique way of accessing the API, but with the help of some core unit tests across all the implementations, ensure that it still achieves what it needs to.

**Comment by bobturneruk** [comment]
C++ will be implemented standalone.
