### ISSUE TITLE
Pipeline overview

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#780]
Create some diagrams to illustrate the data pipeline. Put them here: https://scottishcovidresponse.github.io/docs/data_pipeline/

**Comment by bobturneruk** [comment]
https://teams.microsoft.com/l/file/9F7AEF63-776D-4CAD-BB01-877367C9B3AA?tenantId=6e725c29-763a-4f50-81f2-2e254f0133c8&fileType=pptx&objectUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium%2FShared%20Documents%2FGeneral%2FCollaboration%2Fdata%20pipeline%20API%2FData%20pipeline.pptx&baseUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium&serviceName=teams&threadId=19:283c5ea4551344249cc76dd0ecaa4f74@thread.tacv2&groupId=669b45e2-a9a6-4060-ba8a-9ebd3713e367

**Comment by richardreeve** [comment]
Initial work here... https://scottishcovidresponse.github.io/docs/data_pipeline/pipeline/

**Comment by richardreeve** [comment]
Slides are also here - https://teams.microsoft.com/l/file/B21233B0-AE29-42F2-A37E-718273EF42F7?tenantId=6e725c29-763a-4f50-81f2-2e254f0133c8&fileType=pptx&objectUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium%2FShared%20Documents%2FGeneral%2FCollaboration%2Fdata%20pipeline%20API%2FRevised%20data%20pipeline%20-%2020210330.pptx&baseUrl=https%3A%2F%2Fgla.sharepoint.com%2Fsites%2FScottishCOVID-19ResearchConsortium&serviceName=teams&threadId=19:283c5ea4551344249cc76dd0ecaa4f74@thread.tacv2&groupId=669b45e2-a9a6-4060-ba8a-9ebd3713e367

**Comment by bobturneruk** [comment]
See https://scottishcovidresponse.github.io/docs/data_pipeline/introduction/
