### ISSUE TITLE
Repository Names (and "sync tool name")

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#785]
GitHub organisations are often not the easiest to navigate. Having clear and systematic naming of repositories will help.

**Comment by bobturneruk** [comment]
I suggest the following renaming:

| Old Name | New Name |
| --- | --- |
| data_pipeline_api | python_pipeline_api |
| SCRC-Cpp-API | cpp_pipeline_api |
| SCRCdataAPI | r_pipeline_api |
| JAVA-data-pipeline | java_pipeline_api (also make public) |
| DataRegistryUtils.jl | julia_pipeline_api |
| fdp | fairdp_sync_tool |
| data-registry | data-registry (stays same) |

Incidentally, I think these are the total repositories that the data pipeline grant / team are working on.

**Comment by soniamitchell** [comment]
My only comment is that if the R API were ever intended to be published to CRAN, it would be preferable that the repo name match the package name, whatever that might be.

**Comment by bobturneruk** [comment]
Thanks @soniamitchell - I've been lazily pythonic with all the names. Is the proposed name OK for CRAN? Not sure what the rules are...

**Comment by soniamitchell** [comment]
Actually, I have a second comment... data-registry being hyphenated when everything else is underscored makes me uncomfortable... though if I don't look at your list I have no problem with it.

**Comment by bobturneruk** [comment]
I was thinking leave it be as it's OK as it is, but I agree the inconsistency is irksome!

**Comment by soniamitchell** [comment]
> Thanks @soniamitchell - I've been lazily pythonic with all the names. Is the proposed name OK for CRAN? Not sure what the rules are...

No underscores, no hyphens, no dots, just camelcase. I meant more from a descriptive perspective though. Having "R" in the name is fine, but it likely needs some reference to "FDP", and perhaps "API" is unnecessary.

**Comment by mjb3** [comment]
Hi Bob, definitely agree - DataRegistryUtils was started as a sandpit for me to learn about the DR and just spiralled from there. Can we choose something like PipelineAPI.jl instead though so that it adheres to the Julia packaging conventions? I will change the name of the package too (same reason as Sonia)

**Comment by ghost** [comment]
Hyphenate all the others (since they are changing anyway? Don't need to hold a modifier key to type the hyphen.

**Comment by soniamitchell** [comment]
> Hi Bob, definitely agree - DataRegistryUtils was started as a sandpit for me to learn about the DR and just spiralled from there. Can we choose something like PipelineAPI.jl instead though so that it adheres to the Julia packaging conventions? I will change the name of the package too (same reason as Sonia)

This suits me, perhaps rFDP might suit me better though (can't have dots), and FDP.jl? or we could all have different names depending on our convention?

**Comment by bobturneruk** [comment]
Good idea @nathan-cummings-ukaea.

**Comment by kzscisoft** [comment]
Maybe I am not familiar with CRAN enough, but would CRAN care about the repository name? Surely it is the name in the properties file that is what matters.

**Comment by soniamitchell** [comment]
CRAN doesn't care... but it's convention.

**Comment by mjb3** [comment]
> > Hi Bob, definitely agree - DataRegistryUtils was started as a sandpit for me to learn about the DR and just spiralled from there. Can we choose something like PipelineAPI.jl instead though so that it adheres to the Julia packaging conventions? I will change the name of the package too (same reason as Sonia)
> 
> This suits me, perhaps rFDP might suit me better though (can't have dots), or we could all have different names depending on our convention?

No worries, understood. That's just the Julia way I think. Incidentally, I also noticed this among the Julia guidelines so the point you made about FDP might be applicable here too I think:
_Packages that wrap external libraries or programs should be named after those libraries or programs.

    CPLEX.jl wraps the CPLEX library, which can be identified easily in a web search.

    MATLAB.jl provides an interface to call the MATLAB engine from within Julia._

**Comment by soniamitchell** [comment]
Sorry, I kept editing my comment. How about rFDP and FDP.jl or whatever people want to call it?

**Comment by mjb3** [comment]
Suits me, I'll with the flow. Wasn't it decided that we were changing FDP though because it sounds too much like FTP? Or did that get shelved?

**Comment by soniamitchell** [comment]
No idea, I missed the last meeting so may be out of date. Happy with whatever was decided.

**Comment by ghost** [comment]
I don't mind if the names don't all adhere to a common convention - as long as it is unambiguous which is which.

Currently, we have:
![image](https://user-images.githubusercontent.com/55384390/118133381-aebfd180-b3f8-11eb-8eae-6ed24c85026c.png)
![image](https://user-images.githubusercontent.com/55384390/118133454-c4cd9200-b3f8-11eb-8508-346187879e80.png)
![image](https://user-images.githubusercontent.com/55384390/118133493-d020bd80-b3f8-11eb-9590-6dd69e324ec8.png)
![image](https://user-images.githubusercontent.com/55384390/118133530-da42bc00-b3f8-11eb-88aa-92f644aff565.png)
![image](https://user-images.githubusercontent.com/55384390/118133568-e62e7e00-b3f8-11eb-8bd3-c69add357f45.png)
![image](https://user-images.githubusercontent.com/55384390/118133615-f34b6d00-b3f8-11eb-80c7-aa4e21c50d2a.png)

**Comment by ghost** [comment]
Just looking at the language tag from GitHub doesn't always help either, the actual Python API code for example is inside one of the ones tagged as C++

It's just a bit of a mess currently.

**Comment by soniamitchell** [comment]
I don't look at anyone else's repos so it doesn't bother me, happy to go with what's easiest for everyone else.

**Comment by bobturneruk** [comment]
> Just looking at the language tag from GitHub doesn't always help either, the actual Python API code for example is inside one of the ones tagged as C++

> It's just a bit of a mess currently.

Related https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/784

**Comment by bobturneruk** [comment]
Do we also need a new organisation (for the data pipeline grant outputs)?

**Comment by bobturneruk** [comment]
Perhaps people should propose a name that works for the language they're operating in - I agree with @nathan-cummings-ukaea - we don't need to be systematic. `python_pipeline_api` works for Python, I think. If we all have a name we want to use by the next time we meet, we can see if there's any major objections.

For the sync tool, if we're not using `fdp` or `fairdp`, I suggest `p`ipeline-`r`egistry `a`lignment `t`ool.

**Comment by richardreeve** [comment]
So - we have the FAIRDataPipeline organisation, and the `fair` command line tool. We do still need to decide on names for:

- [x] C++ data pipeline API (currently cppDataPipeline) - @kzscisoft 
- [x] Java data pipeline API (currently javaDataPipeline) - @B0SKAMP 
- [x] Python data pipeline API (currently pyDataPipeline) - @DennisReddyhoff 
- [x] Julia data pipeline API (currently DataPipeline.jl) - @mjb3 
- [x] R data pipeline API (currently rDataPipeline) - @soniamitchell 
- [x] the data registry (currently data-registry) - @nathan-cummings-ukaea / @alahiff 

Some of these may be complete - we just need to agree on them in the meeting on Tuesday 29th. These repos also need to be moved into the new organisation if they aren't already:
- [x] Python - ScottishCovidResponse/data_pipeline_api#121
- [x] Java - ScottishCovidResponse/JAVA-data-pipeline#1
- [x] registry - ScottishCovidResponse/data-registry#61

Can they be moved before the meeting on Tuesday please?

**Comment by richardreeve** [comment]
DPAPIs renamed to langDataPipeline.
