### ISSUE TITLE
Force of infection

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#81]
Split virus into two distinct categories: Force of infection (airborne and instantaneous) and environmental reservoir (Contact and decays over time).

**Comment by richardreeve** [comment]
Now ScottishCovidResponse/Simulation.jl#26 has been merged is this fixed @claireh93?

**Comment by claireh93** [comment]
Closed with ScottishCovidResponse/Simulation.jl#26
