### ISSUE TITLE
Write outputs as a raster

### ISSUE THREAD

**Issue by claireh93** [ScottishCovidResponse/SCRCIssueTracking#85]
Also need functionality to convert and write outputs to a raster for input into GIS. First pass at GIS visualisation being discussed currently.

**Comment by claireh93** [comment]
Currently storing outputs in a 3D array (disease class X grid cell X time), e.g.
https://github.com/ScottishCovidResponse/Simulation.jl/blob/dev/examples/Epidemiology/SEI2HRD_example.jl lines 74-76

**Comment by claireh93** [comment]
We had discussion about storing a raster with several layers (of disease classes, SIR etc) per timepoint. This may become unwieldy if the output raster files are too large, so other approaches may need to be considered.

**Comment by AlexRobson** [comment]
Can more detail to be added to this? I'm looking through the Starter issues, but I can't interpret what this one needs in order to pick it up - thanks

**Comment by claireh93** [comment]
Sure! We are hoping to generate some maps of disease spread over time and need to import the simulated output data into ArcGIS somehow. As a first pass, saving raster files (e.g. GeoTIFF format) would work. In order to do this we would need to convert from the arrays I described above into a raster format, possibly using GDAL or ArchGDAL - the GeoArrays package might also be helpful.
