### ISSUE TITLE
Expand readme

### ISSUE THREAD

**Issue by bobturneruk** [ScottishCovidResponse/SCRCIssueTracking#96]
suggested headings

- Introduction
*Motivation, why is this here.*
- Features
*What does the software do? How does it compare with other similar software? May want to refer to a seperate concept of operations document.*
- Usage
*How do I use the software (in the simplest cases)? This should eventually refer to more in depth docs.*
- Installation
*How do I install the software? What are the system requirements? Conda? Virtual environment?*
- Contributing
*How do I contribute to the project? e.g. Issue>Branch>Commit>PR>(CI)>Review>Merge*
- License
*What license? Link to full license.*

**Comment by magicicada** [comment]
python3 sampleUseOfModel.py sample_input_files/paramsAgeStructured sample_input_files/sample_hb2019_pop_est_2018.sampleCSV  sample_input_files/sample_scotHB_commute_moves_wu01.sampleCSV afilename.pdf

**Comment by magicicada** [comment]
![updated_CompartmentalModel](https://user-images.githubusercontent.com/6224231/81551373-a5310300-9379-11ea-9209-9dc82629cf45.png)

**Comment by magicicada** [comment]
(Upon reflection, the structure is not fully input-file, it's also in some of the setup and the infection process functions, but we could move to making it as external-file-as-possible)
